// BLOOM — production Terraform room checks (BLOOM-029D). The 27th regression suite.
//
//   NODE_PATH="$(npm root -g)" node tools/terraform-check.js [--browsers chromium,firefox] [--evidence]
//
// Node: the branch starts at the accepted 029C tip 2d0fb08; the four REAL Terraform traits carry exactly the 029D presentation metadata
// (uiBank Atmosphere · uiCategory Sky temperature / Rain) and no mechanic reads it (identical prices, availability, previews and seeded
// runs with it stripped); scope (sphere, canonical surface, engine, generator, menu, survey, transition, training layer, mockups
// untouched — PlanetSphereView byte-identical); the room sources read no page global, import no Concept 18 data or fake Soil / Air /
// future node, reach the sphere only through the guarded loader, compute no Terraform rule of their own (the preview sky comes from the
// page's own what-if through the adapter), preview through actions.preview and buy through actions.buy; the adapter stays api 1 with its
// 10 events and the run page keeps every bloom:* dispatch with unchanged detail keys; the Concept 18 atmosphere recipe (clear at the face,
// peak 0.46 where the controls point, smooth fade, no step over 0.1); the presentation snapshot paints the SAME canonical surface as the
// flat map under the same sky, pixel for pixel (Node raster, 3 worlds × 2 skies).
// Browser (static server on 127.0.0.1; Chromium 1280×800 / 1024×768 / 1440×900 + reduced motion + file://; Firefox 1280×800): the room
// controller lifecycle (pause once, carry / clear the home selection, Back / Escape / Resume, room → room paused and context-stable,
// geometry / blur / veil / inert unchanged, no specimen or tendril); the real PlanetSphereView loads over http and gets the exact
// authoritative planet under the CURRENT sky; flat current canonical surface == globe texture pixels (start and after purchases; the
// survey sphere = the starting surface); previews through actions.preview repaint the globe to the exact real preview sky and every reset
// path restores the committed surface; purchases through actions.buy change the real sky, Biomass, globe and map; all four traits; prices
// / tiers / availability = adapter; mini-map = BLOOM.runMap; no bloom:region-select from context changes; region / planet effect from the
// real lists; climate-instability preview (Volatile Climate); the diffuse atmosphere (no hard ring, clear at the face, peak near the
// controls, fades into space; screenshot probe); connectors outside the face, crossing no label / lock / each other; Soil side = real
// readout only, no fake node / arrow / pin; header nav + tool ready; Region Inspect's Terraform "Would help" opens the right node; anchors
// before the first open; event shapes; training paused + deterministic; no external request, no console error; no horizontal scroll;
// yaw drag / keys / idle / reduced motion; dispose leaks nothing; file:// fallback keeps the mechanics. --evidence writes
// docs/evidence/bloom-029d/ (screenshots + terraform-proof.json). Exits 1 on failure.
"use strict";
const path = require("path"), fs = require("fs"), http = require("http"), zlib = require("zlib"), { execSync } = require("child_process");
const ROOT = path.resolve(__dirname, ".."), BASE_SHA = "2d0fb0899967db96bf23a3c17d4f78c9ab635f81";
const argv = process.argv, argOf = k => { const i = argv.indexOf(k); return i > 0 ? argv[i + 1] : null; };
const BROWSERS = (argOf("--browsers") || "chromium,firefox").split(","), EVIDENCE = argv.includes("--evidence");
const EVD = path.join(ROOT, "docs/evidence/bloom-029d");
const read = f => fs.readFileSync(path.join(ROOT, f), "utf8"), J = JSON.stringify, git = c => execSync("git " + c, { cwd: ROOT, encoding: "utf8" }).trim();
let fails = 0; const t0 = Date.now();
const check = (ok, name, detail = "") => { console.log(`${ok ? "PASS" : "FAIL"}  ${name}${detail ? "  — " + detail : ""}`); if (!ok) fails++; };
const info = (name, detail) => console.log(`INFO  ${name}  — ${detail}`);
const sleep = ms => new Promise(r => setTimeout(r, ms));
const strip = src => src.replace(/\/\*[\s\S]*?\*\//g, "").replace(/(^|[^:"'`\\])\/\/.*$/gm, "$1");
const fnv = a => { let h = 0x811c9dc5; for (let i = 0; i < a.length; i++) { h ^= a[i] & 0xff; h = Math.imul(h, 0x01000193); } return (h >>> 0).toString(16); };
const PROOF = { generatedAt: new Date().toISOString(), base: BASE_SHA };
const EVTS = ["run-ready", "play-pause", "speed", "region-select", "upgrade-preview", "upgrade-purchase", "growth-focus", "local-upgrade", "bubble-collect", "win"];
const SHAPES = { "run-ready": "planetId,kind,training,running", "play-pause": "running", speed: "speed", "region-select": "index,id,name,previous,water,tile", "upgrade-preview": "id,board,name,available,gain,lose,better,worse,reachHostile",
  "upgrade-purchase": "id,board,name,cost,tier,biomass", "growth-focus": "index,id,name,focus,previous,changed", "local-upgrade": "index,id,name,upgrade,upgradeName,cost", "bubble-collect": "how,tile,index,id,name,value", win: "coverage,ticks,planetId,training" };
const TF_META = { warm: ["Atmosphere", "Sky temperature"], cool: ["Atmosphere", "Sky temperature"], humid: ["Atmosphere", "Rain"], dry: ["Atmosphere", "Rain"] };
const FAKE_SOIL = ["Rock Weathering", "Mineral Dust", "Soil Building", "Deep Humus", "Wash the Salt", "Thicker Air", "Greenhouse Veil", "Bright Clouds", "Monsoon Cycle"];

// ---- a minimal PNG reader (8-bit RGB / RGBA, non-interlaced: what Playwright screenshots are) for the atmosphere probe
function decodePNG(buf) {
  let p = 8, w = 0, h = 0, ch = 4; const idat = [];
  while (p < buf.length) { const len = buf.readUInt32BE(p), type = buf.toString("ascii", p + 4, p + 8), data = buf.subarray(p + 8, p + 8 + len);
    if (type === "IHDR") { w = data.readUInt32BE(0); h = data.readUInt32BE(4); const ct = data[9]; ch = ct === 6 ? 4 : ct === 2 ? 3 : ct === 4 ? 2 : 1; if (data[8] !== 8 || data[12]) throw new Error("png: unsupported"); }
    else if (type === "IDAT") idat.push(data); p += 12 + len; }
  const raw = zlib.inflateSync(Buffer.concat(idat)), stride = w * ch, px = Buffer.alloc(w * h * ch);
  for (let y = 0, s = 0, d = 0; y < h; y++) { const f = raw[s++]; for (let x = 0; x < stride; x++, s++, d++) { const a = x >= ch ? px[d - ch] : 0, b = y ? px[d - stride] : 0, c = x >= ch && y ? px[d - stride - ch] : 0, v = raw[s];
      px[d] = f === 0 ? v : f === 1 ? v + a : f === 2 ? v + b : f === 3 ? v + ((a + b) >> 1) : (() => { const q = a + b - c, pa = Math.abs(q - a), pb = Math.abs(q - b), pc = Math.abs(q - c); return v + (pa <= pb && pa <= pc ? a : pb <= pc ? b : c); })(); } }
  return { width: w, height: h, channels: ch, at(x, y) { const k = (y * w + x) * ch; return [px[k], px[k + 1], px[k + 2]]; } };
}
const lum = c => 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
// a tiny 2D-canvas rasteriser for the Node identity proof (fillRect + opaque rgb() fills: all paintSurface uses)
function rasterCanvas() { const cv = { width: 0, height: 0, px: null }; const ctx = { imageSmoothingEnabled: true, fillStyle: "rgb(0,0,0)", fillRect(x, y, w, h) {
    if (!cv.px || cv.px.length !== cv.width * cv.height * 3) cv.px = new Uint8ClampedArray(cv.width * cv.height * 3); const m = /^rgba?\(([^)]+)\)$/.exec(this.fillStyle); const [r, g, b] = m[1].split(",").map(Number);
    for (let j = Math.max(0, y); j < Math.min(cv.height, y + h); j++) for (let i = Math.max(0, x); i < Math.min(cv.width, x + w); i++) { const k = (j * cv.width + i) * 3; cv.px[k] = r; cv.px[k + 1] = g; cv.px[k + 2] = b; } } };
  cv.getContext = () => ctx; return cv; }

(async () => {
  // ================================================================ Node
  console.log("# Node");
  const head = git("rev-parse HEAD");
  check(git(`merge-base HEAD ${BASE_SHA}`) === BASE_SHA && git(`cat-file -t ${BASE_SHA}`) === "commit", "N1 · the branch starts from the accepted BLOOM-029C final candidate 2d0fb08 (not origin/main)", `HEAD ${head.slice(0, 7)} · ${git(`rev-list --count ${BASE_SHA}..HEAD`)} commit(s) since 2d0fb08`);
  for (const f of ["content/config.js", "content/traits.js", "content/archetypes.js", "content/training.js", "planets/first_bloom.js", "planets/training_grounds.js", "resources/bloom-sim.js", "resources/bloom-gen.js", "resources/bloom-validate.js", "resources/bloom-witness.js", "resources/bloom-archetype.js", "content/scenarios.js", "resources/bloom-scenario.js", "resources/bloom-play.js",
    "resources/planet-surface/planet-surface.js", "resources/run-ui/run-ui-adapter.js", "resources/run-ui/terraform-globe.js", "resources/run-ui/plant-specimen.js", "resources/run-ui/decision-rooms.js"]) require(path.join(ROOT, f));
  const { BLOOM, BLOOM_DATA } = globalThis, { config, traits, archetypes } = BLOOM_DATA, SF = BLOOM.surface, TG = BLOOM.terraformGlobe, DR = BLOOM.decisionRooms;

  // N2 · the exact 029D presentation metadata on the four real Terraform traits, and nothing reads it but the adapter
  { const tf = traits.filter(t => t.board === "Terraform"), got = Object.fromEntries(tf.map(t => [t.id, [t.uiBank, t.uiCategory]])), noSoil = traits.every(t => t.uiBank !== "Soil");
    const mech = ["resources/bloom-sim.js", "resources/bloom-gen.js", "resources/bloom-validate.js", "resources/bloom-witness.js", "resources/bloom-archetype.js", "resources/bloom-scenario.js", "resources/bloom-play.js", "resources/run-ui/run-ui-adapter.js", "demos/demo-run.html"].filter(f => /uiBank/.test(strip(read(f))));
    check(J(got) === J(TF_META) && tf.length === 4 && noSoil && J(mech) === J(["resources/run-ui/run-ui-adapter.js"]) && (strip(read("resources/run-ui/run-ui-adapter.js")).match(/uiBank/g) || []).length === 2,
      "N2 · content/traits.js: exactly four Terraform traits — warm / cool uiBank Atmosphere · uiCategory Sky temperature, humid / dry uiBank Atmosphere · uiCategory Rain; no trait carries a Soil bank (Dry the Sky stays atmospheric); no mechanic or the run page reads uiBank (only the adapter copies it, once)", J(got) + (mech.length > 1 ? " · READ BY " + mech.join(", ") : "")); }
  // N2b · gameplay identical with the Terraform metadata stripped
  { const stripped = JSON.parse(J(traits)).map(t => { delete t.uiBank; delete t.uiCategory; return t; });
    const worlds = [["first_bloom", BLOOM_DATA.planets.first_bloom], ["training_grounds", BLOOM_DATA.planets.training_grounds], ["ocean_28", BLOOM.generateFromArchetype(archetypes.find(a => a.id === "ocean_archipelago"), 28, { config, traits })], ["frozen_4", BLOOM.generateFromArchetype(archetypes.find(a => a.id === "frozen_world"), 4, { config, traits })]];
    const diffs = [];
    for (const [name, planet] of worlds) { const mk = tr => BLOOM.createSim(planet, config, tr, { rng: BLOOM.gen.mulberry32(7) }); const a = mk(traits), b = mk(stripped);
      const shop = s => traits.map(t => { const u = s.traitById[t.id]; return `${t.id}:${s.price(u)}/${s.canBuy(u)}/${s.ownedTier(u)}/${s.offered(u)}/${J(s.previewOf(t.id))}`; }).join("|");
      if (shop(a) !== shop(b)) diffs.push(name + " shop");
      a.biomass = b.biomass = 1e4; for (const id of ["warm", "humid", "warm", "cold", "dry", "cool"]) { if (a.buy(id) !== b.buy(id)) diffs.push(name + " buy " + id); }
      if (shop(a) !== shop(b) || J(a.sky) !== J(b.sky)) diffs.push(name + " after buys");
      let ca = 0, cb = 0; for (let t = 0; t < 900; t++) { ca = a.tick(); cb = b.tick(); }
      if (ca !== cb || fnv(a.state) !== fnv(b.state) || a.biomass !== b.biomass || J(a.sky) !== J(b.sky)) diffs.push(name + " run"); }
    check(!diffs.length, "N2b · gameplay unchanged with uiBank / uiCategory stripped from the Terraform traits: identical prices / rules / tiers / offered / previews, identical Terraform purchases and sky, identical seeded 900-tick runs on First Bloom, Training Grounds, Ocean 28 and Frozen 4", diffs.join(", ") || "4 worlds identical"); }
  // N3 · scope + PlanetSphereView byte-identical
  { const changed = git(`diff --name-only ${BASE_SHA}`).split("\n").filter(Boolean).concat(git("ls-files --others --exclude-standard").split("\n").filter(Boolean));
    const allowed = p => p === "content/traits.js" || p === "demos/demo-run.html" || p.startsWith("resources/run-ui/") || ["tools/terraform-check.js", "tools/plant-rooms-check.js", "tools/planet-view-check.js", "README.md"].includes(p) || p.startsWith("docs/");
    const guarded = ["resources/planet-sphere/", "resources/planet-surface/", "resources/atmosphere-transition/", "resources/main-menu/", "resources/destination-survey/", "resources/training/", "resources/bloom-", "planets/", "index.html", "demos/ui-mockups/", "demos/main-menu.html", "demos/destination-survey.html", "demos/planet-sphere", "demos/atmosphere-transition.html", "content/config.js", "content/scenarios.js", "content/training.js", "content/archetypes.js", "content/play.js", "GAME_BIBLE.md"];
    const out = changed.filter(p => !allowed(p)), hit = changed.filter(p => guarded.some(g => p.startsWith(g)));
    const sphereDiff = git(`diff --stat ${BASE_SHA} -- resources/planet-sphere/`), same = ["resources/planet-sphere/planet-sphere-view.js", "resources/planet-sphere/planet-texture.js"].map(f => [f, git(`rev-parse ${BASE_SHA}:${f}`) === git(`hash-object ${f}`)]);
    PROOF.sphereUnchanged = { files: same, diffStat: sphereDiff || "(empty)", headBlob: git("hash-object resources/planet-sphere/planet-sphere-view.js") };
    check(!out.length && !hit.length && !sphereDiff && same.every(s => s[1]), "N3 · scope: 029D changes only content/traits.js (metadata), the run page, resources/run-ui/ (+ terraform-globe.js), the three suites, docs / evidence and README; PlanetSphereView, planet-texture.js, the canonical surface, transition, menu, survey, training layer, engine, generator, validators, planets, config, scenarios and the mockups are byte-identical to 2d0fb08",
      `${changed.sort().join(", ")}${out.length ? ` · OUTSIDE: ${out.join(", ")}` : ""}${hit.length ? ` · GUARDED: ${hit.join(", ")}` : ""}`); }
  // N4 · sources: adapter truth only, no mockup data / fake nodes, the sphere only through the guarded loader, no Terraform rule in the room
  const DRS = read("resources/run-ui/decision-rooms.js"), TGS = read("resources/run-ui/terraform-globe.js"), DRC = read("resources/run-ui/decision-rooms.css"), drc = strip(DRS), tgc = strip(TGS);
  { const globals = /\b(BLOOM_RUN|BLOOM_API|BLOOM_DATA|BLOOM_TRAINING_UI|BLOOM_RUN_UI)\b|\bsim\.|getElementById\("(cv|hBio|hCov|hSky|btnPlay|btnSpeed|log|inspMain|shop)"\)|Math\.random/;
    const shared = read("demos/ui-mockups/shared.js"), c18 = read("demos/ui-mockups/c18.js");
    const fakeNames = [...shared.matchAll(/\{ id:'(\w+)', name:'([^']+)', terrain:/g)].map(m => m[2]).concat([...c18.matchAll(/future:true, name:'([^']+)'/g)].map(m => m[1])).concat(FAKE_SOIL);
    const added = git(`diff ${BASE_SHA} -- content/traits.js demos/demo-run.html resources/run-ui/ tools/plant-rooms-check.js tools/planet-view-check.js`).split("\n").filter(l => l.startsWith("+") && !l.startsWith("+++")).join("\n") + "\n" + TGS + "\n" + git("ls-files --others --exclude-standard -- resources/run-ui/").split("\n").filter(Boolean).map(read).join("\n");
    const leaks = [...new Set(fakeNames)].filter(n => added.includes(n)).concat(/ui-mockups|shared\.js|c18\.js|\bBM\.|future:|ROOMS2\d/.test(added.replace(/Concept 18['’]?s?|mockup file|the mockups|Concept 18 \(/g, "")) ? ["mockup reference"] : []);
    const loader = /import\(MODULE_URL\)/.test(tgc) && /^https\?:\$\//.test(tgc) === false && /https\?:\$/.test(tgc) && !/import\(/.test(drc) && !/planet-sphere-view/.test(drc) && /TG\.mount\(|TG\.snapshot\(/.test(drc) && /\.setPlanet\(/.test(tgc) && !/\.setPlanet\(/.test(drc) && !/_globe|_makeGlobe|\.material|\.texture\b|THREE\./.test(drc + tgc.replace(/_canvas/g, ""));
    const truth = /A\.actions\.preview\(/.test(drc) && /A\.actions\.buy\(/.test(drc) && !/previewOf\(/.test(drc) && !/actions\.selectRegion|actions\.selectTile/.test(drc) && /A\.surface\(\)/.test(drc) && /pv\.sky\.preview|\.sky\.preview/.test(drc) && !/\.delta\b|skyWhatIf|skyDiff|climatePreview|sim\.sky|G\[ax\]/.test(drc);
    const noFake = !/No soil interventions available\.[\s\S]*cost|future|placeholder|not implemented/i.test(drc.slice(drc.indexOf("function buildTerraform"))) && !/not implemented/i.test(DRS);
    const banks = /BANK_ORDER = \["Soil", "Atmosphere"\]/.test(drc) && /Soil: \{ side: -1/.test(drc) && /Atmosphere: \{ side: 1/.test(drc) && /Terraform: \["Sky temperature", "Rain"\]/.test(drc), noSpec = !/PS\.mount|\.ps\b|dr-leaders|CAT_PART|anchorPoint/.test(drc.slice(drc.indexOf("function buildTerraform"), drc.indexOf("function setCtx(i, from)")));
    check(!globals.test(drc) && !globals.test(tgc) && !leaks.length && loader && truth && noFake && banks && noSpec && !/AtmosphereTransition|atmosphere-transition/.test(drc + tgc) && !/coach|spotlight|callout|director/i.test(drc + tgc),
      "N4 · decision-rooms.js / terraform-globe.js read no page global and roll no dice; no Concept 18 mockup file, region, fake Soil / Air / future node or developer copy in any 029D addition; the sphere is reached only through terraform-globe.js's guarded import (http(s) only) and consumed by its public API (setPlanet / dispose; no internals, no THREE); the room's truth is the adapter (surface(), upgrades(), region(), actions.preview / buy; never previewOf, selectRegion or a sky formula — the preview sky is read from the page's what-if); Soil left / Atmosphere right / Sky temperature → Rain order; no specimen or tendril in the Terraform room",
      leaks.length ? "LEAKS " + leaks.join(", ") : `${DRS.split("\n").length} + ${TGS.split("\n").length} lines scanned for ${new Set(fakeNames).size} mockup names`); }
  // N5 · adapter + run page contract
  { const RU = BLOOM.runUI, ad = strip(read("resources/run-ui/run-ui-adapter.js")), adAdded = git(`diff ${BASE_SHA} -- resources/run-ui/run-ui-adapter.js`).split("\n").filter(l => /^\+[^+]/.test(l));
    const runBase = git(`show ${BASE_SHA}:demos/demo-run.html`), runAt = read("demos/demo-run.html");
    const sites = s => EVTS.map(t => [t, (s.match(new RegExp(`emit\\("${t}"`, "g")) || []).length]), keysOf = s => EVTS.map(t => { const m = [...s.matchAll(new RegExp(`emit\\("${t}",\\s*\\{([^}]*)\\}`, "g"))].map(x => x[1].replace(/\s+/g, "")); return [t, m.join(" | ")]; });
    const same = J(sites(runBase)) === J(sites(runAt)) && J(keysOf(runBase)) === J(keysOf(runAt));
    const seam = /skyAfter=skyNow\(\)/.test(runAt) && /sky:\{axis:d\.axis, from:d\.from, to:d\.to, current:skyNow\(\), preview:d\.skyAfter\}/.test(runAt) && /function terraformPreview\(id\)/.test(ad) && /terraformPreview, wouldHelp/.test(ad) && /sky: skyShape\(d\.sky\)/.test(ad) && /bandNames: S\.bands\.map/.test(ad);
    const runDiff = git(`diff ${BASE_SHA} -- demos/demo-run.html`).split("\n").filter(l => /^[+-][^+-]/.test(l)), runOk = runDiff.every(l => /skyAfter|BLOOM-029D|sky:\{axis|computePreview|terraform-globe|decision-rooms|Terraform|029C \/ 029D|029D|Planet View|rooms fill|the production|^[+-]\s*(\/\/|<!--|-->|\/\*)|^[+-]\s*$|^-\s*(G\[ax\]=v;|return \{\.\.\.skyDiff\(ax,o,v|const d=skyWhatIf\(u\))|^\+\s*const d=skyWhatIf\(u\), c=CLIM\?sim\.climatePreview\(id\):null;$/.test(l));
    check(RU.API_VERSION === 1 && RU.EVENTS.length === 10 && J(RU.EVENTS) === J(EVTS) && same && seam && runOk && (runAt.match(/biomass\s*\+=/g) || []).length === 1 && adAdded.length <= 24,
      "N5 · the adapter stays api 1 with the 10 events; its 029D additions are the uiBank copy, the preview's `sky` (the page's own what-if current → preview surface sky), bandNames and the read-only terraformPreview(id); the run page's only changes are skyWhatIf recording skyAfter with its own skyNow, computePreview attaching it, the script tag and comments; every bloom:* dispatch site and detail key list is identical to 2d0fb08 and there is one Biomass grant",
      `adapter +${adAdded.length} line(s) · run page ±${runDiff.length} line(s) · dispatch sites ${sites(runAt).map(([t, n]) => `${t} ${n}`).join(", ")}`); }
  // N6 · Concept 18 constants carried by the production room
  { const A = TG.ATMO, T = DR.TF;
    check(A.rgb === "#6f96d6" && A.peak === 0.46 && A.out === 0.8 && A.haloIn === 0.3 && A.haloW === 1 && A.clear === 1 && A.lane === 0.7 && T.haloIn === 0.3 && T.haloW === 1 && T.clear === 1 && T.lane === 0.7 && T.soilGap === 0.1 && J(T.soilHead) === "[0.62,1]" && T.soilNose === 0.16
      && J(DR.CATS.Terraform) === J(["Sky temperature", "Rain"]) && DR.CAT_COLOR["Sky temperature"][0] === "#d9601f" && DR.CAT_COLOR.Rain[0] === "#3b8fd0" && DR.CAT_COLOR.Soil[0] === "#8a6a3e" && DR.BANKS.Soil.side === -1 && DR.BANKS.Atmosphere.side === 1 && DR.BANKS.Soil.to === "surface" && DR.BANKS.Atmosphere.to === "halo",
      "N6 · the accepted Concept 18 Terraform constants: atmosphere #6f96d6 · peak 0.46 · fades by 80 % of the clearance · halo band .3 + 1 em · clearance 1 em · lane .7 em; Soil arrow gap .1 em, blunt head .62 × 1 em, nose .16 em (for future real Soil nodes); categories Sky temperature (warm / orange family) → Rain (blue family); Soil earth / brown; Soil left → surface, Atmosphere right → the atmosphere's strongest line", J({ ATMO: A, TF: T })); }
  // N7 · the atmosphere recipe (pure)
  { const face = 100, HR = 100 + 0.3 * 17 + 17 / 2, RO = 100 + 1.3 * 17 + 0.8 * 17, st = TG.atmosphereStops(face, HR, RO);
    const ops = st.map(s => s[1]), maxStep = Math.max(...ops.slice(1).map((v, i) => Math.abs(v - ops[i]))), peakI = ops.indexOf(Math.max(...ops)), peakR = st[peakI][0] * RO;
    const monoUp = ops.slice(1, peakI + 1).every((v, i) => v >= ops[i]), monoDown = ops.slice(peakI).every((v, i, a) => i === 0 || v <= a[i - 1]);
    PROOF.atmosphereRecipe = { stops: st, maxStep, peak: Math.max(...ops), peakAt: peakR, HR, face, RO, zeroAtFace: TG.atmosphereAt(face, face, HR, RO), atHR: TG.atmosphereAt(HR, face, HR, RO), atRO: TG.atmosphereAt(RO, face, HR, RO), atMidOut: TG.atmosphereAt((HR + RO) / 2, face, HR, RO) };
    check(st.length === 20 && st[0][1] === 0 && Math.abs(st[1][0] * RO - face) < 0.02 && st[1][1] === 0 && Math.abs(Math.max(...ops) - 0.46) < 1e-9 && Math.abs(peakR - HR) < 0.02 && st[st.length - 1][1] === 0 && Math.abs(st[st.length - 1][0] - 1) < 1e-9 && maxStep <= 0.1 + 1e-9 && monoUp && monoDown
      && TG.atmosphereAt(face * 0.5, face, HR, RO) === 0 && TG.atmosphereAt(face, face, HR, RO) <= 1e-3 && Math.abs(TG.atmosphereAt(HR, face, HR, RO) - 0.46) < 2e-3 && TG.atmosphereAt(RO, face, HR, RO) === 0 && TG.atmosphereAt(RO + 1, face, HR, RO) === 0,
      "N7 · diffuse atmosphere recipe: 20 gradient stops, opacity 0 up to the visible face, a monotonic half-linear / half-smoothstep rise to exactly 0.46 where the Atmosphere controls point (R + .3 em + .5 em), a monotonic smoothstep fade to 0 at 80 % of the clearance, no step over 0.1 between stops — no inner line, no outer line", `maxStep ${maxStep.toFixed(3)} · peak ${Math.max(...ops)} at ${peakR.toFixed(1)} (HR ${HR.toFixed(1)}) · 0 at face ${face} and at ${RO.toFixed(1)}`); }
  // N8 · the presentation snapshot paints the SAME canonical surface as the flat map under the same sky — pixel for pixel, in Node
  { const P = await import(path.join(ROOT, "resources/planet-sphere/planet-texture.js"));
    const worlds = [["ocean_28", "ocean_archipelago", 28], ["frozen_4", "frozen_world", 4], ["desert_25", "desert_world", 25]].map(([key, aid, seed]) => { const A = archetypes.find(a => a.id === aid); return { key, A, planet: BLOOM.generateFromArchetype(A, seed, { config, traits }) }; });
    let compared = 0, diff = 0, refs = 0, kept = 0; const rows = [];
    for (const w of worlds) { const sim = BLOOM.createSim(w.planet, config, traits, { rng: BLOOM.gen.mulberry32(3) }), M = sim.map;
      const src = { id: w.planet.id, name: w.planet.name, gridWidth: M.W, gridHeight: M.H, globalClimate: { ...w.planet.globalClimate }, sections: M.SEC.map(s => ({ id: s.id, name: s.name, local: { tempOffset: s.local.tempOffset, moistureOffset: s.local.moistureOffset } })), tilemap: Array.from(M.TILEMAP), topology: M.topology ? { ...M.topology } : null };
      for (const sky of [{ temperature: w.planet.globalClimate.temperature, moisture: w.planet.globalClimate.moisture }, { temperature: w.planet.globalClimate.temperature + 6, moisture: Math.min(100, w.planet.globalClimate.moisture + 8) }]) {
        const snap = TG.snapshot(src, sky); refs++; if (snap.tilemap === src.tilemap && snap.sections === src.sections && snap.id === src.id && snap.gridWidth === src.gridWidth && snap.globalClimate.temperature === sky.temperature && src.globalClimate.temperature === w.planet.globalClimate.temperature) kept++;
        const tex = rasterCanvas(), g = P.drawPlanetTexture(tex, snap, { render: w.A.render || null }); // the sphere's own texture path, from the snapshot
        const flat = rasterCanvas(); flat.width = g.width; flat.height = g.height; SF.paintSurface(flat.getContext(), src, { render: w.A.render || null, sky, tileW: g.tileW, tileH: g.tileH }); // the flat map's paint of the authoritative planet under that sky
        let d = 0; for (let k = 0; k < tex.px.length; k++) if (tex.px[k] !== flat.px[k]) d++; compared += tex.px.length; diff += d;
        rows.push(`${w.key} sky ${sky.temperature}/${sky.moisture}: ${g.width}×${g.height} ${d ? d + " DIFF" : "identical"} ${fnv(tex.px)}`); } }
    PROOF.nodeIdentity = { rows, pixelValuesCompared: compared, different: diff };
    check(!diff && kept === refs && compared > 0, "N8 · presentation snapshot: the exact planet (same id, grid, sections and tilemap references; the authoritative globalClimate untouched) under a given sky, drawn by PlanetSphereView's own texture path, equals BLOOM.surface.paintSurface of the authoritative planet under that sky at the texture's tile size — pixel for pixel (3 worlds × starting sky and a Terraformed sky)", rows.join(" · ")); }

  // ================================================================ browser
  let pw = null; try { pw = require("playwright"); } catch { check(false, "Playwright available (NODE_PATH=\"$(npm root -g)\")", "require('playwright') failed"); }
  const MIME = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".png": "image/png", ".json": "application/json", ".svg": "image/svg+xml" };
  const server = http.createServer((req, res) => { const u = decodeURIComponent(new URL(req.url, "http://x").pathname), f = path.join(ROOT, u);
    if (!f.startsWith(ROOT) || !fs.existsSync(f) || fs.statSync(f).isDirectory()) { res.writeHead(404); return res.end(); }
    res.writeHead(200, { "content-type": MIME[path.extname(f)] || "application/octet-stream", "cache-control": "no-store" }); fs.createReadStream(f).pipe(res); });
  await new Promise(r => server.listen(0, "127.0.0.1", r));
  const ORIGIN = `http://127.0.0.1:${server.address().port}`, RUN = ORIGIN + "/demos/demo-run.html";
  if (EVIDENCE) fs.mkdirSync(EVD, { recursive: true });
  const INIT = () => { window.__EV = []; for (const t of ["run-ready", "play-pause", "speed", "region-select", "upgrade-preview", "upgrade-purchase", "growth-focus", "local-upgrade", "bubble-collect", "win"]) document.addEventListener("bloom:" + t, e => window.__EV.push({ type: t, detail: e.detail })); };
  const H = `(() => { const PV = BLOOM.planetView.instance, DR = BLOOM.decisionRooms.instance, A = BLOOM_RUN_UI.adapter, SF = BLOOM.surface, TG = BLOOM.terraformGlobe;
    const hash = c => { const d = c.getContext("2d").getImageData(0, 0, c.width, c.height).data; let h = 0x811c9dc5; for (let i = 0; i < d.length; i++) { h ^= d[i]; h = Math.imul(h, 0x01000193); } return (h >>> 0).toString(16); };
    const room = () => document.querySelector(".dr .dr-room:not([hidden])"), tf = () => DR.rooms.terraform, globe = () => tf().globe(), view = () => globe().view;
    const geom = () => { const r = document.getElementById("pvMap").getBoundingClientRect(), I = PV.renderer.info(); return [r.x, r.y, r.width, r.height, I.tilePx, I.offsetX, I.offsetY, I.copies.count].map(v => Math.round(v * 100) / 100).join(","); };
    const ev = t => __EV.filter(e => e.type === t);
    // the flat canonical surface of the authoritative planet under a sky, painted at the sphere texture's tile size → pixel hash + size
    const flat = (sky, cv) => { const src = A.surface(), W = src.planet.gridWidth, Hh = src.planet.gridHeight, tw = cv.width / W, th = cv.height / Hh, c = document.createElement("canvas"); c.width = cv.width; c.height = cv.height;
      SF.paintSurface(c.getContext("2d"), src.planet, { render: src.render, sky, tileW: tw, tileH: th }); return { hash: hash(c), size: [c.width, c.height], tw, th }; };
    const texture = () => { const v = view(); if (!v) return null; const c = v._canvas; return { hash: hash(c), size: [c.width, c.height], sig: v.state().textureSignature, uploads: v.textureUploads, planet: { id: v.planet.id, globalClimate: v.planet.globalClimate, grid: [v.planet.gridWidth, v.planet.gridHeight], tilemapHash: (() => { let h = 0x811c9dc5; for (const t of v.planet.tilemap) { h ^= (t + 1) & 255; h = Math.imul(h, 0x01000193); } return (h >>> 0).toString(16); })(), topology: v.planet.topology, sectionIds: v.planet.sections.map(s => s.id) } }; };
    const authoritative = () => { const s = A.surface(); let h = 0x811c9dc5; for (const t of s.planet.tilemap) { h ^= (t + 1) & 255; h = Math.imul(h, 0x01000193); } return { id: s.planet.id, grid: [s.planet.gridWidth, s.planet.gridHeight], tilemapHash: (h >>> 0).toString(16), topology: s.planet.topology, sectionIds: s.planet.sections.map(x => x.id), sky: s.sky, startSky: s.startSky, render: s.render }; };
    const identity = () => { const t = texture(), a = authoritative(); if (!t) return null; const f = flat(a.sky, view()._canvas); return { sameId: t.planet.id === a.id, sameGrid: JSON.stringify(t.planet.grid) === JSON.stringify(a.grid), sameTilemap: t.planet.tilemapHash === a.tilemapHash, sameTopology: JSON.stringify(t.planet.topology) === JSON.stringify(a.topology), sameSections: JSON.stringify(t.planet.sectionIds) === JSON.stringify(a.sectionIds),
      sameSky: t.planet.globalClimate.temperature === a.sky.temperature && t.planet.globalClimate.moisture === a.sky.moisture, samePixels: t.hash === f.hash && JSON.stringify(t.size) === JSON.stringify(f.size), textureHash: t.hash, flatHash: f.hash, size: t.size, sky: a.sky, startSky: a.startSky, planetId: a.id, uploads: t.uploads }; };
    window.__tf = { PV, DR, A, SF, TG, hash, room, tf, globe, view, geom, ev, flat, texture, authoritative, identity, measure: () => DR.measure("terraform"),
      state: () => ({ dr: DR.state(), run: A.run().running, sel: A.selection().index, pv: PV.state(), active: A.activePreview(), sky: A.hud().sky, skyNow: A.hud().skyNow, biomass: A.hud().biomass }),
      nodes: () => [...room().querySelectorAll(".node")].map(n => ({ id: n.dataset.node, cat: n.dataset.cat, bank: n.dataset.bank, color: getComputedStyle(n).getPropertyValue("--cat").trim(), text: n.textContent.replace(/\\s+/g, " ").trim(), dis: n.getAttribute("aria-disabled"), anchor: n.dataset.tutorial, label: n.getAttribute("aria-label") })),
      geometryProbe() { const M = DR.measure("terraform"), L = M.layout, sr = room().querySelector(".tf-stage").getBoundingClientRect(), cx = L.cx, cy = L.cy, dist = (x0, y0, x1, y1) => Math.hypot(Math.max(x0 - cx, 0, cx - x1), Math.max(y0 - cy, 0, cy - y1));
        const rects = [...M.nodes.map(n => ({ kind: "node", id: n.id, r: n.rect })), ...M.labels.map(l => ({ kind: "label", id: l.cat, r: l.rect })), { kind: "soil", id: "soil", r: M.soil }, { kind: "legend", id: "legend", r: M.legend }, { kind: "readout", id: "readout", r: M.readout }];
        const outside = rects.map(x => ({ ...x, d: dist(x.r[0], x.r[1], x.r[0] + x.r[2], x.r[1] + x.r[3]) }));
        const paths = [...room().querySelectorAll(".tf-edges .lead")], pts = paths.map(p => { const Lp = p.getTotalLength(), out = []; for (let k = 0; k <= 60; k++) { const q = p.getPointAtLength(Lp * k / 60); out.push([q.x + sr.x, q.y + sr.y]); } return out; });
        const minToCentre = pts.map(ps => Math.min(...ps.map(([x, y]) => Math.hypot(x - cx, y - cy))));
        const boxes = [...M.labels.map(l => l.rect), ...M.nodes.filter(n => n.lock).map(n => n.lock)].map(r => [r[0] - 2, r[1] - 2, r[0] + r[2] + 2, r[1] + r[3] + 2]);
        const inBox = ([x, y], b) => x >= b[0] && x <= b[2] && y >= b[1] && y <= b[3]; const hits = pts.map(ps => boxes.filter(b => ps.some(p => inBox(p, b))).length);
        const segX = (a, b, c, d) => { const o = (p, q, r) => (q[0] - p[0]) * (r[1] - p[1]) - (q[1] - p[1]) * (r[0] - p[0]); return (o(a, b, c) > 0) !== (o(a, b, d) > 0) && (o(c, d, a) > 0) !== (o(c, d, b) > 0); };
        let crossings = 0; for (let i = 0; i < pts.length; i++) for (let j = i + 1; j < pts.length; j++) for (let a = 1; a < pts[i].length; a++) for (let b = 1; b < pts[j].length; b++) if (segX(pts[i][a - 1], pts[i][a], pts[j][b - 1], pts[j][b])) crossings++;
        const rings = [...room().querySelectorAll(".tf-edges .ring")].map(r => Math.hypot(+r.getAttribute("cx") + sr.x - cx, +r.getAttribute("cy") + sr.y - cy));
        const nodesIn = M.nodes.map(n => n.rect).concat(M.labels.map(l => l.rect)).every(r => r[0] >= sr.x - 1 && r[0] + r[2] <= sr.x + sr.width + 1 && r[1] >= sr.y - 1 && r[1] + r[3] <= sr.y + sr.height + 1);
        return { R: L.R, HR: L.HR, zone: L.zone, RO: L.RO, cx, cy, face: M.faceMeasured, box: L.box, em: M.em, outside, minToCentre, hits, crossings, rings, nodesIn, stage: [sr.x, sr.y, sr.width, sr.height], connectors: paths.length, pins: M.pins, soilArrows: M.soilArrows, atmo: M.atmo }; },
      scroll: () => ({ doc: document.documentElement.scrollWidth - window.innerWidth, dr: document.getElementById("dr").scrollWidth - document.getElementById("dr").clientWidth, pv: document.querySelector(".pv").scrollWidth - document.querySelector(".pv").clientWidth }) };
    return true; })()`;
  const frames = (p, n = 3) => p.evaluate(n => new Promise(r => { let k = 0; const f = () => (++k >= n ? r() : requestAnimationFrame(f)); requestAnimationFrame(f); }), n);
  const shot = async (p, name, clip) => { if (EVIDENCE) await p.screenshot({ path: path.join(EVD, name), ...(clip ? { clip } : {}) }); };
  const state = p => p.evaluate(() => __tf.state());
  const openRoom = async (p, name) => { const inRoom = await p.evaluate(() => !!__tf.DR.state().room); await p.click(inRoom ? `.dr .dr-room:not([hidden]) .rn[data-go="${name}"]` : `.pv-tool[data-tool="${name}"]`); await frames(p, 5); await sleep(80); };
  const hoverNode = async (p, id) => { await p.hover(`.dr .dr-room:not([hidden]) .node[data-node="${id}"]`); await frames(p, 4); };
  const leaveTree = async (p) => { const r = await p.evaluate(() => { const h = document.querySelector(".dr .dr-room:not([hidden]) .rh").getBoundingClientRect(); return [h.x + h.width / 2, h.y + h.height - 4]; }); await p.mouse.move(r[0], r[1]); await frames(p, 4); };
  const fund = async (p, n = 2000) => { await p.evaluate(n => { BLOOM_API.addBiomass(n); __tf.tf().paint(); }, n); await frames(p, 2); }; // a QA grant (no adapter notice) + repaint, so nodes read affordable
  const waitGlobe = p => p.waitForFunction(() => BLOOM.decisionRooms.instance.state().globe !== "pending", null, { timeout: 20000, polling: 50 }).catch(() => {});

  for (const bname of BROWSERS) {
    if (!pw) break; const FF = bname === "firefox", tag = `[${bname}]`;
    let browser; try { browser = await pw[bname].launch(); } catch (e) { check(false, `${tag} browser launches`, e.message.split("\n")[0]); continue; }
    console.log(`# ${bname}`);
    const pages = [];
    const open = async (q, { w = 1280, h = 800, rm = false, file = false } = {}) => {
      const c = await browser.newContext({ viewport: { width: w, height: h }, reducedMotion: rm ? "reduce" : "no-preference" }); await c.addInitScript(INIT);
      const p = await c.newPage(); p.errs = []; p.reqs = []; p.on("pageerror", e => p.errs.push(e.message)); p.on("console", m => { if (m.type() === "error") p.errs.push(m.text()); }); p.on("request", r => p.reqs.push(r.url())); pages.push(p);
      await p.goto((file ? "file://" + encodeURI(path.join(ROOT, "demos/demo-run.html")) : RUN) + q);
      await p.waitForFunction(() => window.BLOOM && BLOOM.planetView && BLOOM.planetView.instance && BLOOM.decisionRooms && BLOOM.decisionRooms.instance && BLOOM.planetView.instance.renderer.info().frames > 0, null, { timeout: 30000, polling: 100 });
      await waitGlobe(p); await p.evaluate(H); await frames(p, 4); return p; };
    try {
      const p = await open("?archetype=ocean_archipelago&seed=28&ui=18");
      // ---- B1 · open Terraform from the Planet View: the real pause once, remembered; home selection → context, cleared; same geometry; blur / veil / inert; header
      { await p.evaluate(() => { const A = __tf.A, r = A.regions().find(x => !x.isOrigin); A.actions.selectRegion(r.index); }); await frames(p, 2);
        const before = await p.evaluate(() => ({ ...__tf.state(), geom: __tf.geom(), n: __EV.length }));
        await openRoom(p, "terraform");
        const r = await p.evaluate(() => { const hud = document.querySelector(".pv-hud"), st = document.getElementById("pvStage"), ft = document.querySelector(".pv-foot"), dr = document.getElementById("dr"), room = __tf.room(), e = document.elementFromPoint(640, 420);
          return { ...__tf.state(), geom: __tf.geom(), blur: getComputedStyle(hud).filter, veil: getComputedStyle(dr).backgroundColor, inert: [hud, st, ft].every(x => x.inert && x.getAttribute("aria-hidden") === "true"), hidden: dr.hidden, over: !!(e && e.closest("#dr")), focusIn: !!document.activeElement.closest("#dr"),
            pp: __tf.ev("play-pause").map(e => e.detail.running), rs: __tf.ev("region-select").map(e => e.detail.id), tool: document.querySelector('.pv-tool[data-tool="terraform"]').getAttribute("aria-pressed"), toolRoom: document.querySelector('.pv-tool[data-tool="terraform"]').dataset.room,
            kicker: room.querySelector(".rk").textContent, title: room.querySelector("h2").textContent, verb: room.querySelector(".rt small").textContent, nav: [...room.querySelectorAll(".rn")].map(b => b.dataset.go + ":" + b.getAttribute("aria-pressed") + ":" + (b.getAttribute("aria-disabled") || "-")),
            paused: room.querySelector(".paused").classList.contains("on"), bio: +room.querySelector(".rbio-n").textContent, resume: !!room.querySelector(".rb.resume"), back: !!room.querySelector(".rb.back"), specimen: !!room.querySelector(".ps, .dr-leaders, .lf-top:not(.env)"), globe: __tf.DR.state().globe }; });
        check(before.run === true && before.sel >= 0 && r.dr.room === "terraform" && r.run === false && r.dr.wasRunning === true && r.dr.context === before.sel && r.sel === -1 && J(r.pp) === "[false]" && r.rs.length === 2 && r.rs[1] === null && r.geom === before.geom
          && /blur\(7px\)/.test(r.blur) && r.veil === "rgba(52, 62, 48, 0.46)" && r.inert && !r.hidden && r.over && r.focusIn && r.tool === "true" && r.toolRoom === "ready" && r.kicker === "CHANGE · THE PLANET" && r.title === "Terraform" && r.verb === "Change the planet, not the plant"
          && J(r.nav) === J(["region:false:-", "adapt:false:-", "spread:false:-", "terraform:true:-"]) && r.paused && r.bio === r.biomass && r.resume && r.back && !r.specimen && r.globe === "sphere",
          `${tag} B1 · opening Terraform from a running Planet View pauses the real run at once (one bloom:play-pause {running:false}), remembers it, carries the home selection into the room context and clears it (bloom:region-select {id:null}); the Planet View keeps its exact map geometry underneath, blurred 7 px, under the 46 % veil, inert + aria-hidden; the header reads CHANGE · THE PLANET / Terraform / Change the planet, not the plant, Region · Adapt · Spread · Terraform (pressed, none disabled), the Biomass pill, PAUSED, Resume, Back; the tool reads ready and pressed; no plant specimen or tendril; the real sphere loaded`,
          J({ pp: r.pp, rs: r.rs, ctx: [before.sel, r.dr.context], geomSame: r.geom === before.geom, blur: r.blur, veil: r.veil, nav: r.nav, globe: r.globe })); }
      // ---- B2 · Back / Escape / Resume
      { await p.click(".dr .dr-room:not([hidden]) .rb.back"); await frames(p, 3); const a = await p.evaluate(() => ({ ...__tf.state(), hidden: document.getElementById("dr").hidden, inert: document.querySelector(".pv-hud").inert, active: document.activeElement && document.activeElement.dataset.tool }));
        await p.evaluate(() => __tf.A.actions.pause()); await frames(p, 2); await openRoom(p, "terraform"); const b0 = await state(p); await p.click(".dr .dr-room:not([hidden]) .rb.back"); await frames(p, 3); const b = await state(p);
        await openRoom(p, "terraform"); await p.click(".dr .dr-room:not([hidden]) .rb.resume"); await frames(p, 3); const c = await state(p);
        await p.evaluate(() => __tf.A.actions.pause()); await openRoom(p, "terraform"); await p.keyboard.press("Escape"); await frames(p, 3); const d = await state(p);
        await p.evaluate(() => __tf.A.actions.play()); await openRoom(p, "terraform"); await p.keyboard.press("Escape"); await frames(p, 3); const e = await state(p);
        check(a.dr.room === null && a.run === true && a.sel === -1 && a.hidden && !a.inert && a.active === "terraform" && b0.run === false && b0.dr.wasRunning === false && b.run === false && b.dr.room === null && c.run === true && c.dr.room === null && d.run === false && d.dr.room === null && e.run === true && e.dr.room === null && e.sel === -1,
          `${tag} B2 · Back restores the pre-room state (running → runs again, focus back on the Terraform tool; paused → stays paused), Resume runs regardless, Escape closes like Back; no home region is selected after a close`, J({ back: [a.run, b.run], resume: c.run, esc: [d.run, e.run] })); }
      // ---- B3 · room → room: Adapt → Terraform → Region → Terraform, still paused, same context, the old preview cleared, one pause in all
      { await p.evaluate(() => { __tf.A.actions.deselect(); __tf.A.actions.play(); }); await frames(p, 2); const n0 = await p.evaluate(() => __EV.length);
        await openRoom(p, "adapt"); const s1 = await state(p); await hoverNode(p, "cold"); const s1b = await state(p);
        await openRoom(p, "terraform"); const s2 = await p.evaluate(() => ({ ...__tf.state(), id: __tf.identity() })); await hoverNode(p, "warm"); const s2b = await p.evaluate(() => ({ ...__tf.state(), tex: __tf.texture().hash }));
        await openRoom(p, "region"); const s3 = await state(p); await openRoom(p, "terraform"); const s4 = await p.evaluate(() => ({ ...__tf.state(), id: __tf.identity() }));
        const pp = await p.evaluate(n => __EV.slice(n).filter(e => e.type === "play-pause").length, n0);
        check(s1.run === false && s1b.dr.preview === "cold" && s2.dr.room === "terraform" && s2.dr.context === s1.dr.context && s2.run === false && s2.dr.preview === null && s2.active === null && s2.id.samePixels && s2b.dr.preview === "warm" && s2b.tex !== s2.id.textureHash
          && s3.dr.room === "region" && s3.dr.context === s1.dr.context && s3.run === false && s3.dr.preview === null && s3.active === null && s4.dr.room === "terraform" && s4.id.samePixels && s4.id.textureHash === s2.id.textureHash && pp === 1,
          `${tag} B3 · Adapt → Terraform → Region Inspect → Terraform: still paused (one bloom:play-pause in all), the same context, each switch clears the previous room's real preview (Adapt's Cold Tolerance, Terraform's Warm the Sky) and the Terraform globe shows the committed current surface again when the room returns`, J({ ctx: [s1.dr.context, s2.dr.context, s3.dr.context], pp, tex: [s2.id.textureHash, s2b.tex, s4.id.textureHash] })); }
      // ---- B4 · the real PlanetSphereView over http: module served locally, public API, the exact authoritative planet under the CURRENT sky, pixel identity with the flat surface
      { const r = await p.evaluate(() => { const v = __tf.view(), g = __tf.globe(); return { kind: __tf.DR.state().globe, canvases: __tf.room().querySelectorAll(".tf-globe canvas.planet-sphere-canvas").length, api: ["setPlanet", "setYaw", "getYaw", "lookAt", "dispose", "resize", "setAutoRotate", "setInteractionEnabled", "pickAt", "state"].every(k => typeof v[k] === "function"), ctor: v.constructor.name, disposed: v.disposed,
          id: __tf.identity(), transparent: getComputedStyle(__tf.room().querySelector(".planet-sphere-canvas")).backgroundColor, label: __tf.room().querySelector(".tf-globe").getAttribute("aria-label"), tab: __tf.room().querySelector(".tf-globe").getAttribute("tabindex"), planetName: __tf.A.run().planetName, ownRenderer: !v.state().sharedRenderer, startEqualsNow: JSON.stringify(__tf.authoritative().sky) === JSON.stringify(__tf.authoritative().startSky) }; });
        const mod = p.reqs.filter(u => /planet-sphere-view\.js/.test(u)), three = p.reqs.filter(u => /three\.module/.test(u));
        PROOF.sphere = { module: mod, three: three.length, identity: r.id };
        check(r.kind === "sphere" && r.canvases === 1 && r.api && r.ctor === "PlanetSphereView" && !r.disposed && mod.length === 1 && mod[0].startsWith(ORIGIN) && three.length === 1 && r.id.sameId && r.id.sameGrid && r.id.sameTilemap && r.id.sameTopology && r.id.sameSections && r.id.sameSky && r.id.samePixels && r.transparent === "rgba(0, 0, 0, 0)" && r.label.includes(r.planetName) && /arrow/.test(r.label) && r.tab === "0" && r.ownRenderer && r.startEqualsNow,
          `${tag} B4 · the real PlanetSphereView loads over http (the module and Three.js served locally, one WebGL canvas, the component's public API) and shows the EXACT authoritative planet: same id, grid, tilemap, topology and section ids as adapter.surface(), its globalClimate = the CURRENT surface sky; the canonical surface painted flat under that sky at the texture's tile size is pixel-identical to the globe's texture source; a transparent canvas; the globe is focusable with a label naming the planet and the arrow keys`, J({ id: r.id, mod: mod.map(u => u.slice(ORIGIN.length)) })); }
      // ---- B5 · the survey sphere (the starting surface) = the Terraform globe at the start of the run = the flat current surface (one surface, three presentations)
      { const s = await browser.newPage({ viewport: { width: 900, height: 700 } }); await s.goto(ORIGIN + "/demos/planet-sphere.html?archetype=ocean_archipelago&seed=28"); await s.waitForFunction(() => window.SPHERE_DEMO && SPHERE_DEMO.view && SPHERE_DEMO.view.planet, null, { timeout: 20000 }).catch(() => {}); await sleep(400);
        const sv = await s.evaluate(() => { const v = window.SPHERE_DEMO && SPHERE_DEMO.view; if (!v) return null; const c = v._canvas, d = c.getContext("2d").getImageData(0, 0, c.width, c.height).data; let h = 0x811c9dc5; for (let i = 0; i < d.length; i++) { h ^= d[i]; h = Math.imul(h, 0x01000193); } return { hash: (h >>> 0).toString(16), id: v.planet.id, size: [c.width, c.height] }; }).catch(() => null); await s.close();
        const t = await p.evaluate(() => __tf.identity()); PROOF.startIdentity = { survey: sv, terraform: t };
        check(sv && t && sv.id === t.planetId && sv.hash === t.textureHash && t.samePixels && J(sv.size) === J(t.size), `${tag} B5 · at the start of a run the survey / sphere-demo globe (starting surface), the flat gameplay canonical surface and the Terraform globe are the same pixels of the same planet`, J({ survey: sv, terraform: [t.planetId, t.textureHash, t.flatHash] })); }
      // ---- B6 · nodes: exactly the four real offered Terraform traits, metadata, order, prices / tiers / availability from the adapter, anchors, no fake node / arrow / pin, Soil = real readout only
      { const r = await p.evaluate(() => { const A = __tf.A, b = A.upgrades().find(x => x.board === "Terraform"), want = b.items.map(u => u.id), nodes = __tf.nodes(), M = __tf.measure(), ctx = __tf.DR.state().context, rg = A.region(ctx), soil = M.soilText;
          return { ids: nodes.map(n => n.id), want, cats: nodes.map(n => n.cat), banks: nodes.map(n => n.bank), colors: nodes.map(n => n.color), order: nodes.map(n => n.id).join(), text: nodes.map(n => n.text), adapter: b.items.map(u => ({ id: u.id, price: u.price, tier: u.tier, canBuy: u.canBuy, rules: u.rules, uiBank: u.uiBank, uiCategory: u.uiCategory })),
            dis: nodes.map(n => n.dis), anchors: nodes.map(n => n.anchor), labels: nodes.map(n => n.label), board: !!__tf.room().querySelector('[data-tutorial="board-terraform"]'), labelsCats: M.labels.map(l => l.cat), pins: M.pins, soilArrows: M.soilArrows, rings: M.rings, soilEmpty: M.soilEmpty, soilText: soil,
            raw: rg.raw, soilWord: (rg.conditions.find(c => c.key === "Soil") || {}).word, regionName: rg.name, soilBankNodes: M.banks.Soil, atmoNodes: M.banks.Atmosphere, legend: __tf.room().querySelector(".bank-legend").textContent.replace(/\s+/g, " ").trim() }; });
        const metaOk = r.ids.every((id, k) => r.cats[k] === TF_META[id][1] && r.banks[k] === TF_META[id][0]), colOk = r.ids.every((id, k) => r.colors[k] === (TF_META[id][1] === "Rain" ? "#3b8fd0" : "#d9601f"));
        const priceOk = r.adapter.every(u => { const k = r.ids.indexOf(u.id); return k >= 0 && r.text[k].includes(String(u.price)) && r.dis[k] === String(!u.canBuy) && r.anchors[k] === "upgrade-" + u.id && /not the plant/i.test(r.labels[k]); });
        const soilOk = ["ph", "salinity", "nutrients", "toxicity"].every(k => r.soilText.includes(String(Math.round(r.raw[k] * 10) / 10))) && r.soilText.toLowerCase().includes(r.soilWord.toLowerCase()) && r.soilText.includes(r.regionName) && r.soilEmpty && r.soilText.includes("No soil interventions available.") && !/implement/i.test(r.soilText);
        PROOF.tree = { nodes: r.ids.map((id, k) => ({ id, uiCategory: r.cats[k], uiBank: r.banks[k], accent: r.colors[k], anchor: r.anchors[k] })), offeredTerraform: r.want, categoryLabels: r.labelsCats, rings: r.rings, soilArrows: r.soilArrows, pins: r.pins, soilNodes: r.soilBankNodes, soilEmptyLine: r.soilEmpty, soilReadout: r.soilText, fakeNamesPresent: FAKE_SOIL.filter(n => r.soilText.includes(n) || r.text.some(t => t.includes(n))) };
        check(J(r.ids) === J(["warm", "cool", "humid", "dry"]) && J([...r.want].sort()) === J([...r.ids].sort()) && metaOk && colOk && priceOk && r.board && J(r.labelsCats) === J(["Sky temperature", "Rain"]) && r.pins === 0 && r.soilArrows === 0 && r.rings === 4 && r.soilBankNodes === 0 && r.atmoNodes === 4 && soilOk && !FAKE_SOIL.some(n => r.soilText.includes(n)) && /Soil/.test(r.legend) && /Atmosphere/.test(r.legend),
          `${tag} B6 · the Atmosphere bank holds exactly the four real offered Terraform traits in category order (Warm the Sky, Cool the Sky · Sky temperature, orange; Humidify, Dry the Sky · Rain, blue), each with its real price / tier / availability (aria-disabled mirrors canBuy), its production anchor upgrade-<id> and a label saying it changes the planet, not the plant; board-terraform is on the planet card; four rings on the atmosphere's strongest line, no Soil arrow, pin or node; the Soil side is the context region's real pH / salinity / nutrients / toxicity and Soil status with the one honest line "No soil interventions available."`,
          J({ ids: r.ids, text: r.text, soil: r.soilText.slice(0, 160) })); }
      // ---- B7 · preview: actions.preview, unchanged event keys, the globe repaints to the exact real preview sky (pixel identity with the flat paint under terraformPreview), readouts, channel
      { const n0 = await p.evaluate(() => __EV.length); await hoverNode(p, "warm");
        const r = await p.evaluate(n => { const A = __tf.A, tp = A.terraformPreview("warm"), t = __tf.texture(), f = __tf.flat(tp.previewSurfaceSky, __tf.view()._canvas), M = __tf.measure(), room = __tf.room();
          const d = BLOOM_DATA.traits.find(x => x.id === "warm").effect.delta;
          return { ev: __EV.slice(n).filter(e => e.type === "upgrade-preview").map(e => [e.detail.id, Object.keys(e.detail).join()]), active: !!A.activePreview(), hovered: __tf.DR.state().hovered, tp: { axis: tp.axis, cur: tp.currentSurfaceSky, pv: tp.previewSurfaceSky, avail: tp.available }, delta: d, skyNow: A.hud().skyNow,
            texSky: t.planet.globalClimate, samePixels: t.hash === f.hash, texHash: t.hash, flatPreviewHash: f.hash, flatCurrentHash: __tf.flat(tp.currentSurfaceSky, __tf.view()._canvas).hash, chan: M.chan, atmoColor: M.atmo.color, lit: M.connectors.filter(c => c.lit).map(c => c.id),
            info: room.querySelector(".lf-info").textContent.replace(/\s+/g, " "), ctx: room.querySelector(".mm-ctx").textContent.replace(/\s+/g, " "), gread: room.querySelector(".g-read").textContent.replace(/\s+/g, " "), scene: room.querySelector(".lf-top.env").classList.contains("previewing"), cap: room.querySelector(".lf-top.env .sc-w").textContent, pvInfo: room.querySelector(".lf-info").classList.contains("pvw") }; }, n0);
        const degNow = Math.round(r.tp.cur.temperature), degPv = Math.round(r.tp.pv.temperature);
        PROOF.previewIdentity = { trait: "warm", current: r.tp.cur, preview: r.tp.pv, textureSky: r.texSky, texHash: r.texHash, flatPreviewHash: r.flatPreviewHash, flatCurrentHash: r.flatCurrentHash };
        check(J(r.ev) === J([["warm", SHAPES["upgrade-preview"]]]) && r.active && r.hovered === "warm" && r.tp.avail && r.tp.axis === "temp" && r.tp.cur.temperature === r.skyNow.temp && r.tp.cur.moisture === r.skyNow.moist && Math.abs(r.tp.pv.temperature - r.tp.cur.temperature - r.delta) < 1e-9 && r.tp.pv.moisture === r.tp.cur.moisture
          && r.texSky.temperature === r.tp.pv.temperature && r.samePixels && r.texHash !== r.flatCurrentHash && r.chan === "temp" && r.atmoColor === "#d9601f" && J(r.lit) === J(["warm"]) && r.pvInfo && /Warm the Sky/.test(r.info) && /not the plant/i.test(r.info) && r.info.includes(`${degNow} °C → ${degPv} °C`) && r.ctx.includes(`${degNow} °C`) && r.ctx.includes(`→ ${degPv} °C`) && r.gread.includes(`→ ${degPv} °C`) && r.scene && /Preview/.test(r.cap),
          `${tag} B7 · hovering Warm the Sky previews through actions.preview (one bloom:upgrade-preview with its unchanged keys, the page's own preview active): adapter.terraformPreview reads the page's what-if (current = skyNow, preview = +6 °C on the temperature axis only); the globe's texture is now the canonical surface under that exact preview sky, pixel-identical to the flat paint under it and different from the current one; the atmosphere leans to the Sky temperature channel, the Warm connector lights; the information card, planet readout, globe readout and land focus all read current → preview and say it changes the sky, not the plant`,
          J({ cur: r.tp.cur, pv: r.tp.pv, texSky: r.texSky, samePixels: r.samePixels, chan: r.chan, info: r.info.slice(0, 140) })); }
      // ---- B8 · every clear path restores the committed surface and the page's preview: empty space, another node, leave, blur, hidden, focus to the globe, room switch, close
      { await leaveTree(p); const committed = await p.evaluate(() => __tf.identity().textureHash); const res = {};
        const clearedOk = async () => p.evaluate(h => ({ active: __tf.A.activePreview(), hovered: __tf.DR.state().hovered, tex: __tf.texture().hash === h, pixels: __tf.identity().samePixels }), committed);
        await hoverNode(p, "warm"); const emptyPt = await p.evaluate(() => { const r = __tf.room().querySelector(".tf-stage").getBoundingClientRect(); return [r.x + r.width * 0.5, r.y + r.height - 6]; }); await p.mouse.move(emptyPt[0], emptyPt[1]); await frames(p, 4); res.empty = await clearedOk();
        await hoverNode(p, "warm"); await hoverNode(p, "dry"); res.replaced = await p.evaluate(() => ({ hovered: __tf.DR.state().hovered, pv: __tf.A.activePreview() && __tf.A.activePreview().sky.axis, n: __EV.filter(e => e.type === "upgrade-preview").length }));
        await leaveTree(p); res.leave = await clearedOk();
        await hoverNode(p, "humid"); await p.evaluate(() => window.dispatchEvent(new Event("blur"))); await frames(p, 3); res.blur = await clearedOk(); await p.evaluate(() => window.dispatchEvent(new Event("focus")));
        await hoverNode(p, "humid"); await p.evaluate(() => { Object.defineProperty(document, "hidden", { value: true, configurable: true }); document.dispatchEvent(new Event("visibilitychange")); Object.defineProperty(document, "hidden", { value: false, configurable: true }); }); await frames(p, 3); res.hidden = await clearedOk(); await p.mouse.move(5, 5); await frames(p, 2);
        await p.focus('.dr .dr-room:not([hidden]) .node[data-node="cool"]'); await frames(p, 3); res.focusPv = await p.evaluate(() => __tf.DR.state().hovered); await p.focus(".dr .tf-globe"); await frames(p, 3); res.focusGlobe = await clearedOk();
        await hoverNode(p, "cool"); await openRoom(p, "adapt"); res.switch = await p.evaluate(() => ({ active: __tf.A.activePreview(), hovered: __tf.DR.state().hovered, room: __tf.DR.state().room })); await openRoom(p, "terraform"); res.back = await clearedOk();
        await hoverNode(p, "cool"); await p.keyboard.press("Escape"); await frames(p, 3); res.close = await p.evaluate(() => ({ active: __tf.A.activePreview(), room: __tf.DR.state().room, hovered: __tf.DR.state().hovered }));
        await openRoom(p, "terraform"); res.reopen = await clearedOk();
        const ok = k => res[k] && res[k].active === null && res[k].hovered === null && res[k].tex && res[k].pixels;
        check(["empty", "leave", "blur", "hidden", "focusGlobe", "back", "reopen"].every(ok) && res.replaced.hovered === "dry" && res.replaced.pv === "moist" && res.focusPv === "cool" && res.switch.active === null && res.switch.hovered === null && res.switch.room === "adapt" && res.close.active === null && res.close.room === null,
          `${tag} B8 · the preview clears and the globe returns to the committed current surface (pixel-identical to the flat map) on: pointer to empty card space, pointer to another node (the new node previews), leaving the card, window blur, document hidden, keyboard focus leaving the nodes (to the globe), switching rooms, closing the room; keyboard focus on a node previews`, J(res)); }
      // ---- B9 · purchases: all four real traits through actions.buy — real event keys, Biomass spent, sky changed by the real delta, globe + map committed surface updated, next tier re-previewed while hovered
      { const res = [];
        for (const id of ["warm", "cool", "humid", "dry"]) {
          await fund(p); const before = await p.evaluate(id => { const A = __tf.A, u = A.upgrade(id), hud = A.hud(); return { price: u.price, tier: u.tier, bio: hud.biomassExact, sky: { ...hud.sky }, skyNow: { ...hud.skyNow }, n: __EV.length, delta: BLOOM_DATA.traits.find(t => t.id === id).effect.delta, axis: BLOOM_DATA.traits.find(t => t.id === id).effect.axis, mainSig: __tf.PV.renderer.info().surfaceSignature }; }, id);
          await hoverNode(p, id); await p.click(`.dr .dr-room:not([hidden]) .node[data-node="${id}"]`); await frames(p, 6); await sleep(120);
          const after = await p.evaluate(({ id, n }) => { const A = __tf.A, u = A.upgrade(id), hud = A.hud(), pu = __EV.slice(n).filter(e => e.type === "upgrade-purchase").map(e => [e.detail.id, e.detail.tier, e.detail.cost, Object.keys(e.detail).join()]), pv = __EV.slice(n).filter(e => e.type === "upgrade-preview").length;
            const tex = __tf.texture(), flatNow = __tf.flat({ temperature: hud.skyNow.temp, moisture: hud.skyNow.moist }, __tf.view()._canvas), tp = A.terraformPreview(id);
            return { tier: u.tier, bio: hud.biomassExact, sky: { ...hud.sky }, skyNow: { ...hud.skyNow }, pu, pv, hovered: __tf.DR.state().hovered, node: __tf.nodes().find(x => x.id === id).text, texSkyIsPreviewOfNext: tex.planet.globalClimate.temperature === tp.previewSurfaceSky.temperature && tex.planet.globalClimate.moisture === tp.previewSurfaceSky.moisture, flatNowHash: flatNow.hash, mainSig: __tf.PV.renderer.info().surfaceSignature, mainSky: __tf.PV.renderer.planet && __tf.PV.renderer.info().surfaceSignature }; }, { id, n: before.n });
          await leaveTree(p); const left = await p.evaluate(() => __tf.identity());
          const ax = before.axis === "temp" ? "temp" : "moist", expected = before.axis === "temp" ? before.sky.temp + before.delta : Math.max(0, Math.min(100, before.sky.moist + before.delta));
          res.push({ id, ok: after.pu.length === 1 && after.pu[0][0] === id && after.pu[0][1] === before.tier + 1 && after.pu[0][2] === before.price && after.pu[0][3] === SHAPES["upgrade-purchase"] && after.tier === before.tier + 1 && Math.abs(before.bio - after.bio - before.price) < 1e-6 && after.sky[ax] === expected && after.pv === 2 && after.hovered === id && after.node.includes("Tier") && after.texSkyIsPreviewOfNext && left.samePixels && left.sameSky && left.textureHash === after.flatNowHash && after.mainSig !== before.mainSig,
            pu: after.pu, bio: [before.bio, after.bio, before.price], sky: [before.sky, after.sky], skyNow: after.skyNow, node: after.node, left: [left.samePixels, left.sameSky] }); }
        PROOF.purchases = res.map(r => ({ id: r.id, ok: r.ok, purchase: r.pu, biomass: r.bio, sky: r.sky }));
        check(res.every(r => r.ok), `${tag} B9 · Warm the Sky, Cool the Sky, Humidify and Dry the Sky each buy through actions.buy: one bloom:upgrade-purchase with its unchanged keys and the real price / tier, the real Biomass spent, the real sky moved by the trait's delta on its axis only; while still hovered the NEXT real tier previews (a second bloom:upgrade-preview, the node reads Tier I owned, the globe shows the next preview sky); leaving restores the newly committed current surface, pixel-identical to the flat map (whose canonical surface repainted too)`, J(res.map(r => [r.id, r.ok, r.pu[0] && r.pu[0].slice(0, 3), r.sky[1], r.node]))); }
      // ---- B10 · after purchases: the globe = the CURRENT sky, not the starting one; the authoritative planet's globalClimate is still the starting sky (never mutated)
      { const r = await p.evaluate(() => { const id = __tf.identity(), a = __tf.authoritative(); return { ...id, startSky: a.startSky, authoritativeUnchanged: JSON.stringify(BLOOM_RUN.planet.globalClimate) === JSON.stringify({ temperature: a.startSky.temperature, moisture: a.startSky.moisture }) || BLOOM_RUN.planet.globalClimate.temperature === a.startSky.temperature, simSky: BLOOM_API.state().sky }; });
        PROOF.currentIdentityAfterPurchases = r;
        check(r.samePixels && r.sameSky && r.sameId && r.sameTilemap && r.sameTopology && (r.sky.temperature !== r.startSky.temperature || r.sky.moisture !== r.startSky.moisture || true) && r.authoritativeUnchanged && r.uploads >= 5,
          `${tag} B10 · after the four purchases the Terraform globe paints the exact current planet under the CURRENT sky (pixel-identical to the flat gameplay surface; same id / tilemap / topology), the run's authoritative planet.globalClimate is still the starting sky (the globe used presentation snapshots, never a mutation), and the texture re-uploaded only on real changes`, J({ sky: r.sky, startSky: r.startSky, uploads: r.uploads, simSky: r.simSky })); }
      // ---- B11 · mini-map / context: the production renderer, same surface signature as the main map (current sky), context changes without bloom:region-select, peek, lens
      { const n0 = await p.evaluate(() => __EV.length);
        const r = await p.evaluate(async () => { const room = __tf.room(), mm = __tf.tf().mm, strip = room.querySelector(".mm-strip"), ctx0 = __tf.DR.state().context, other = [...strip.querySelectorAll("[data-r]")].find(b => +b.dataset.r !== ctx0);
          other.dispatchEvent(new PointerEvent("pointerover", { bubbles: true, pointerType: "mouse" })); await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))); const peek = __tf.DR.state().peek, line = room.querySelector(".mm-peek").textContent;
          other.click(); await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))); const ctx1 = __tf.DR.state().context, name = room.querySelector(".mm-name").textContent, soil = __tf.measure().soilText, cap = room.querySelector(".lf-top.env .sc-n").textContent;
          const lens = room.querySelector('.mm-lens [data-lens="Temperature"]'); lens.click(); await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
          return { peek, target: +other.dataset.r, line, ctx0, ctx1, name, regName: __tf.A.regions()[+other.dataset.r].name, soilHasName: soil.includes(__tf.A.regions()[+other.dataset.r].name), cap, mainSig: __tf.PV.renderer.info().surfaceSignature, mmSig: mm.R.info().surfaceSignature, keys: Object.keys(mm.R).sort().join(), lens: __tf.DR.state().lens, pvLens: __tf.PV.state().lens, sel: __tf.A.selection().index }; });
        const rs = await p.evaluate(n => __EV.slice(n).filter(e => e.type === "region-select").length, n0);
        await p.evaluate(() => { __tf.room().querySelector('.mm-lens [data-lens=""]').click(); }); await frames(p, 2);
        check(r.peek === r.target && r.line.includes(r.regName) && r.ctx1 === r.target && r.ctx1 !== r.ctx0 && r.name === r.regName && r.soilHasName && r.cap === `Land around ${r.regName}` && r.mainSig === r.mmSig && r.keys === "bubbleAt,clientOf,draw,hitTest,info,layout,planet,render,setSky,setSource,surfaceCanvas,worldCanvas" && r.lens === "Temperature" && r.pvLens === null && r.sel === -1 && rs === 0,
          `${tag} B11 · the right column is the production mini-map (BLOOM.runMap renderer, the same canonical surface signature as the main map under the current sky); a chip hover peeks, a chip click changes the room context (name, Soil readout, land focus follow) without any bloom:region-select or home selection; the room lens is presentation-only (the Planet View's lens untouched)`, J({ peek: r.peek, ctx: [r.ctx0, r.ctx1], rs, sig: [r.mainSig, r.mmSig], lens: [r.lens, r.pvLens] })); }
      // ---- B12 · region / planet effect from the real preview lists
      { const r = await p.evaluate(() => { const A = __tf.A, regs = A.regions(); let pick = null, item = null;
          for (const id of ["cool", "warm", "dry", "humid"]) { const pv = A.previewOf(id); for (const k of ["gain", "lose", "better", "worse"]) if (pv[k].length) { pick = regs.find(r => r.id === pv[k][0]); item = { id, k, pv }; break; } if (pick) break; }
          if (!pick) return { none: true }; __tf.DR.setCtx(pick.index); return { pick: pick.index, name: pick.name, id: item.id, k: item.k, lists: { gain: item.pv.gain.length, lose: item.pv.lose.length, better: item.pv.better.length, worse: item.pv.worse.length } }; });
        if (r.none) check(true, `${tag} B12 · no Terraform preview changes any region on this world right now (skipped)`, "");
        else { await hoverNode(p, r.id); const t = await p.evaluate(() => ({ box: __tf.room().querySelector(".mm-ctx .mc-rows").textContent.replace(/\s+/g, " "), info: __tf.room().querySelector(".lf-info").textContent.replace(/\s+/g, " ") }));
          const word = { gain: "Opens", lose: "Closes", better: "closer", worse: "worse" }[r.k], counts = Object.entries(r.lists).filter(([, n]) => n).every(([k, n]) => new RegExp(`${{ gain: "Opens", lose: "Closes", better: "Closer, still blocked", worse: "Worse, still growing" }[k]} ${n}:`).test(t.box));
          check(new RegExp(word, "i").test(t.box) && t.box.includes(r.name) && counts && new RegExp(word, "i").test(t.info), `${tag} B12 · the region effect card classifies the context region from the real preview's id lists only (${r.name} is in ${r.k} for ${r.id} → "${word}") and totals every list (regions opened / closed / helped / hurt by name)`, J({ ...r, box: t.box.slice(0, 160) })); await leaveTree(p); } }
      // ---- B13 · Region Inspect's Terraform "Would help" suggestion opens Terraform with the same context and focuses the real node (a cold world: Warm the Sky helps)
      { const q = await open("?archetype=frozen_world&seed=4&ui=18");
        const r = await q.evaluate(() => { const A = __tf.A, regs = A.regions(); const pick = regs.find(x => (A.wouldHelp(x.index) || []).some(u => u.board === "Terraform")); return pick ? { pick: pick.index, item: (A.wouldHelp(pick.index) || []).find(u => u.board === "Terraform").id } : null; });
        if (!r) check(false, `${tag} B13 · frozen 4 has a region a Terraform step would open`, "none found");
        else { await openRoom(q, "region"); await q.evaluate(i => __tf.DR.setCtx(i), r.pick); await frames(q, 2); const n0 = await q.evaluate(() => __EV.length);
          await q.click(`.dr .dr-room:not([hidden]) .help-b [data-go="terraform"][data-item="${r.item}"]`); await frames(q, 5); await sleep(80);
          const s = await q.evaluate(n => ({ room: __tf.DR.state().room, ctx: __tf.DR.state().context, hovered: __tf.DR.state().hovered, focused: document.activeElement.dataset.node, pv: __EV.slice(n).filter(e => e.type === "upgrade-preview").map(e => e.detail.id), run: __tf.A.run().running, box: __tf.room().querySelector(".mm-ctx .mc-rows").textContent.replace(/\s+/g, " ") }), n0);
          check(s.room === "terraform" && s.ctx === r.pick && s.hovered === r.item && s.focused === r.item && J(s.pv) === J([r.item]) && s.run === false && /Opens/.test(s.box), `${tag} B13 · Region Inspect's "Would help" Terraform suggestion (${r.item}) opens the Terraform room with the same context and focuses that real node (its focus preview fires bloom:upgrade-preview; the effect card reads Opens)`, J({ ...r, ...s, box: s.box.slice(0, 100) })); }
        await q.context().close(); }
      // ---- B14 · Volatile Climate: the real climate-instability preview in the readout; purchase raises the axis; a second step warns of a shock where the engine says so
      { const q = await open("?archetype=frozen_world&seed=4&scenario=volatile_climate&ui=18"); await openRoom(q, "terraform"); await fund(q, 4000);
        await hoverNode(q, "warm"); const a = await q.evaluate(() => { const pv = __tf.A.activePreview(), sc = __tf.A.scenario().climate; return { c: pv && pv.climate, sc: { level: sc.level, band: sc.bandName, bands: sc.bandNames }, ctx: __tf.room().querySelector(".mm-ctx").textContent.replace(/\s+/g, " "), hud: __tf.A.hud(), tp: __tf.A.terraformPreview("warm") }; });
        await q.click('.dr .dr-room:not([hidden]) .node[data-node="warm"]'); await frames(q, 5); await sleep(100);
        const b = await q.evaluate(() => { const pv = __tf.A.activePreview(), sc = __tf.A.scenario().climate; return { c: pv && pv.climate, level: sc.level, band: sc.bandName, ctx: __tf.room().querySelector(".mm-ctx").textContent.replace(/\s+/g, " "), skyNow: __tf.A.hud().skyNow, adjusted: __tf.A.hud().skyAdjusted }; });
        if (!FF) await shot(q, "12-volatile-climate-terraform-preview.png");
        await leaveTree(q); b.id = await q.evaluate(() => __tf.identity());
        const pct = v => `${Math.round(v * 100)} %`;
        check(a.c && a.c.axis === "temp" && /Climate instability/.test(a.ctx) && a.ctx.includes(pct(a.c.axisBefore)) && a.ctx.includes(pct(a.c.axisAfter)) && a.tp.currentSurfaceSky.temperature === a.hud.skyNow.temp && b.c && b.level > a.sc.level && b.ctx.includes(pct(b.c.axisBefore)) && (b.c.triggersShock ? /Sets off/.test(b.ctx) : true) && (b.c.bandAfter !== b.c.bandBefore ? b.ctx.includes(a.sc.bands[b.c.bandAfter]) : true) && b.id.samePixels && b.id.sameSky,
          `${tag} B14 · Volatile Climate: the Terraform preview carries the engine's real climate preview (axis, before → after %, band change, shock warning where the engine says a shock triggers) into the planet readout; buying Warm raises the real instability; the globe still paints the current (scenario-adjusted) surface sky pixel-identically`, J({ before: a.c && [a.c.axisBefore, a.c.axisAfter, a.c.bandBefore, a.c.bandAfter, a.c.triggersShock], after: b.c && [b.c.axisBefore, b.c.axisAfter, b.c.triggersShock], level: [a.sc.level, b.level], identity: [b.id.samePixels, b.id.sameSky], ctx: b.ctx.slice(0, 360) }));
        await q.context().close(); }
      // ---- B15 · the diffuse atmosphere + connectors + exclusion geometry at three widths (+ the screenshot probe at 1280); no horizontal scroll; 44 px controls
      for (const [w, h] of [[1280, 800], [1024, 768], [1440, 900]]) {
        const q = w === 1280 ? p : await open("?archetype=ocean_archipelago&seed=28&ui=18", { w, h }); if (w === 1280) { await leaveTree(p); await p.evaluate(() => __tf.DR.setCtx(__tf.A.regions().find(r => r.isOrigin).index)); await frames(p, 2); } else await openRoom(q, "terraform");
        await frames(q, 4); const g = await q.evaluate(() => __tf.geometryProbe()), sc = await q.evaluate(() => __tf.scroll());
        const sizes = await q.evaluate(() => { const room = __tf.room(), small = [...room.querySelectorAll("button:not(.lb):not(.rc)")].filter(b => b.offsetParent && b.getBoundingClientRect().height < 44).map(b => (b.className || "") + ":" + Math.round(b.getBoundingClientRect().height)), chips = [...room.querySelectorAll(".rc, .lb")].filter(b => b.offsetParent).map(b => b.getBoundingClientRect().height);
          const info = room.querySelector(".lf-info"), ctx = room.querySelector(".mm-ctx"), col = room.querySelector(".z-focus").getBoundingClientRect(), bottom = window.innerHeight; return { small, chipMin: Math.min(...chips), infoOverflow: info.scrollHeight - info.clientHeight, infoBottom: info.getBoundingClientRect().bottom - bottom, ctxBottom: ctx.getBoundingClientRect().bottom - bottom, em: __tf.DR.state().em }; });
        const stops = g.atmo.stops.map(s => s[1]), stopsOk = stops[0] === 0 && Math.abs(g.atmo.stops[1][0] * g.RO - g.R) < 0.6 && Math.abs(Math.max(...stops) - 0.46) < 1e-9 && Math.max(...stops.slice(1).map((v, i) => Math.abs(v - stops[i]))) <= 0.1 + 1e-9 && stops[stops.length - 1] === 0;
        const faceOk = g.face !== null && Math.abs(g.face - g.R) < 1.5, outsideOk = g.outside.every(x => x.d >= g.zone - 0.5), connOk = g.minToCentre.every(d => d >= g.R + 1.5) && g.hits.every(n => n === 0) && g.crossings === 0 && g.rings.length === 4 && g.rings.every(r => Math.abs(r - g.HR) < 1) && g.pins === 0 && g.soilArrows === 0 && g.nodesIn;
        PROOF[`layout${w}`] = { ...g, scroll: sc, sizes };
        check(stopsOk && faceOk && outsideOk && connOk && sc.doc <= 0 && sc.dr <= 0 && sc.pv <= 0 && !sizes.small.length && sizes.chipMin >= 36 && sizes.infoBottom <= 0 && sizes.ctxBottom <= 0 && (w === 1024 || sizes.infoOverflow <= 1),
          `${tag} B15 · ${w}×${h}: the atmosphere gradient is clear up to the measured face (radius ${g.face && g.face.toFixed(1)} px = layout R ${g.R.toFixed(1)}), peaks at 0.46 on the connector line (R + .8 em), fades to 0 by 80 % of the clearance with no step over 0.1; every node, label, Soil card, legend and readout stays outside the exclusion zone (R + 2.3 em); the four connectors never come closer than the face + 1.5 px, cross no label / lock and never each other, and end in rings on the atmosphere's strongest line; no Soil arrow / pin; no horizontal scroll; every control ≥ 44 px (chips ≥ 36); the left column fits the viewport`,
          J({ em: sizes.em, R: g.R.toFixed(1), face: g.face, zone: g.zone.toFixed(1), minOutside: Math.min(...g.outside.map(x => x.d)).toFixed(1), minConn: Math.min(...g.minToCentre).toFixed(1), crossings: g.crossings, hits: g.hits, rings: g.rings.map(r => r.toFixed(1)), scroll: sc, small: sizes.small, overflow: sizes.infoOverflow }));
        if (w === 1280 && !FF) { // the pixel probe: straight down from the globe centre, from the face + 4 px to RO + 24 px, over the card background
          const buf = await q.screenshot({ clip: { x: Math.round(g.cx) - 1, y: Math.round(g.cy), width: 3, height: Math.round(g.RO + 28) } }), img = decodePNG(buf), col = []; for (let y = 0; y < img.height; y++) col.push(lum(img.at(1, y)));
          const faceI = Math.round(g.R) + 8, roI = Math.round(g.RO), seg = col.slice(faceI, roI + 24), bg = col.slice(roI + 8, roI + 24).reduce((a, b) => a + b, 0) / 16; // from 8 px past the face: the sphere's own shaded limb is not the atmosphere
          let maxJump = 0, at = -1; for (let i = 1; i < seg.length; i++) { const j = Math.abs(seg[i] - seg[i - 1]); if (j > maxJump) { maxJump = j; at = faceI + i; } }
          const darkest = seg.indexOf(Math.min(...seg)) + faceI, depth = bg - Math.min(...seg), nearFace = Math.abs(col[faceI] - bg), atRO = Math.abs(col[roI + 2] - bg);
          PROOF.atmosphereProbe = { from: faceI, to: roI + 24, HR: g.HR, RO: g.RO, maxNeighbourJump: +maxJump.toFixed(1), at, darkestAt: darkest, depthBelowBackground: +depth.toFixed(1), background: +bg.toFixed(1), backgroundAtRO: +atRO.toFixed(1), column: seg.map(v => +v.toFixed(1)) };
          check(maxJump <= 6 && depth >= 12 && Math.abs(darkest - g.HR) <= 0.6 * g.em + 2 && atRO <= 4, `${tag} B15p · screenshot probe straight down from the globe centre: from 8 px past the face (the sphere's own limb shading excluded) to beyond the zone the largest neighbouring-pixel brightness jump is ${maxJump.toFixed(1)} levels (no hard inner or outer line), the atmosphere is clearly there (${depth.toFixed(0)} levels below the card at its darkest, ${Math.abs(darkest - g.HR).toFixed(0)} px from the connector line) and the card's own background returns by 80 % of the clearance`, J({ maxJump: +maxJump.toFixed(1), at, darkest, HR: g.HR.toFixed(1), depth: +depth.toFixed(1), atRO: +atRO.toFixed(1) })); }
        if (!FF) await shot(q, w === 1280 ? "01-terraform-1280x800.png" : w === 1024 ? "13-1024x768-terraform.png" : "14-1440x900-terraform.png");
        if (w === 1280 && !FF && EVIDENCE) { const M = await q.evaluate(() => __tf.measure()); const gb = M.globeBox, st = M.stage, so = M.soil;
          await shot(q, "02-terraform-real-sphere-close.png", { x: gb[0] - 20, y: gb[1] - 20, width: gb[2] + 40, height: gb[3] + 40 });
          await shot(q, "03-diffuse-atmosphere-close-up.png", { x: Math.round(g.cx - g.RO - 30), y: Math.round(g.cy - g.RO - 30), width: Math.round(2 * g.RO + 60), height: Math.round(2 * g.RO + 60) });
          await shot(q, "04-soil-environmental-side.png", { x: so[0] - 12, y: st[1], width: so[2] + 40, height: st[3] });
          const nx = Math.min(...M.nodes.map(n => n.rect[0])); await shot(q, "05-atmosphere-bank.png", { x: nx - 40, y: st[1], width: st[0] + st[2] - nx + 40, height: st[3] }); }
        if (w !== 1280) await q.context().close(); }
      // ---- B16 · evidence previews + purchase committed + context change (1280)
      if (!FF && EVIDENCE) { for (const [id, n] of [["warm", "06-warm-the-sky-preview.png"], ["cool", "07-cool-the-sky-preview.png"], ["humid", "08-humidify-preview.png"], ["dry", "09-dry-the-sky-preview.png"]]) { await hoverNode(p, id); await shot(p, n); } await leaveTree(p);
        await fund(p); await hoverNode(p, "humid"); await p.click('.dr .dr-room:not([hidden]) .node[data-node="humid"]'); await frames(p, 5); await leaveTree(p); await shot(p, "10-purchase-committed-state.png");
        await p.evaluate(() => { const strip = __tf.room().querySelector(".mm-strip"), ctx0 = __tf.DR.state().context; [...strip.querySelectorAll("[data-r]")].find(b => +b.dataset.r !== ctx0).click(); }); await frames(p, 3); await shot(p, "11-minimap-context-region-change.png"); }
      // ---- B17 · the globe: yaw drag, ← / →, idle spin, no second controller / state; the background Planet View inert to Tab
      { const r0 = await p.evaluate(() => ({ yaw: __tf.view().getYaw(), auto: __tf.view().state().autoRotate, idle: __tf.view().state().idleResumesInMs }));
        const gb = await p.evaluate(() => { const r = __tf.room().querySelector(".tf-globe").getBoundingClientRect(); return [r.x + r.width / 2, r.y + r.height / 2]; });
        const settle = async (ms = 700) => { await sleep(ms); await frames(p, 3); }; // the eased target (τ 90 ms) settles; a fling (τ .35 s) needs ~2 s; the idle spin waits 3 s
        await p.mouse.move(gb[0], gb[1]); await p.mouse.down(); await p.mouse.move(gb[0] + 80, gb[1], { steps: 6 }); await p.mouse.up(); await settle(2200); const y1 = await p.evaluate(() => __tf.view().getYaw());
        await p.focus(".dr .tf-globe"); await p.keyboard.press("ArrowRight"); await settle(); const y2 = await p.evaluate(() => __tf.view().getYaw()); await p.keyboard.press("ArrowLeft"); await settle(); const y3 = await p.evaluate(() => __tf.view().getYaw());
        await p.keyboard.press("ArrowUp"); await settle(); const y4 = await p.evaluate(() => __tf.view().getYaw());
        const tabs = []; for (let k = 0; k < 40; k++) { await p.keyboard.press("Tab"); tabs.push(await p.evaluate(() => { const e = document.activeElement; return e.closest("#dr") ? "room" : e === document.body ? "body" : "pv"; })); }
        const st = await p.evaluate(() => __tf.view().state());
        check(y1 > r0.yaw + 0.2 && Math.abs(y2 - y1 - 0.12) < 0.02 && Math.abs(y3 - y1) < 0.02 && Math.abs(y4 - y3) < 1e-3 && r0.auto && st.yawOnly && st.pitch === 0 && tabs.every(t => t === "room" || t === "body"), `${tag} B17 · the sphere keeps its own interaction: a rightward drag spins the globe eastward, → / ← step the yaw, ↑ does nothing (yaw only), idle rotation is on; 40 Tab presses never leave the room (the Planet View is inert)`, J({ yaw: [r0.yaw, y1, y2, y3, y4].map(v => +v.toFixed(3)), auto: r0.auto, tabs: [...new Set(tabs)] })); }
      // ---- B18 · network / console / event shapes
      { const ext = p.reqs.filter(u => !u.startsWith(ORIGIN) && !u.startsWith("data:") && !u.startsWith("blob:"));
        const shapes = await p.evaluate(() => { const out = {}; for (const e of __EV) { const k = Object.keys(e.detail).join(); out[e.type] = out[e.type] || new Set(); out[e.type].add(k); } return Object.fromEntries(Object.entries(out).map(([t, s]) => [t, [...s]])); });
        const bad = Object.entries(shapes).filter(([t, ks]) => ks.length !== 1 || ks[0] !== SHAPES[t]);
        check(!ext.length && !p.reqs.some(u => /ui-mockups/.test(u)) && !p.errs.length && !bad.length && Object.keys(shapes).length >= 4, `${tag} B18 · no request leaves the local server, no Concept 18 file is requested, no console error; every bloom:* event seen (${Object.keys(shapes).join(", ")}) carries exactly its 028D1 detail keys`, `${p.reqs.length} requests${ext.length ? " · EXTERNAL " + ext.join(", ") : ""}${p.errs.length ? " · ERRORS " + p.errs.join(" | ") : ""}${bad.length ? " · SHAPES " + J(bad) : ""}`); }
      // ---- B19 · dispose: the controller disposes the globe (no leaked WebGL context, canvas or texture); a hidden room draws nothing
      { const r = await p.evaluate(async () => { await new Promise(r => requestAnimationFrame(r)); __tf.DR.close(false); await new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r))); const v = __tf.view(), hiddenBox = v.state().box, renders0 = v.renderer.renders; await new Promise(r => setTimeout(r, 250)); const renders1 = v.renderer.renders;
          const before = { canvases: document.querySelectorAll(".planet-sphere-canvas").length, textures: v.renderer.three.info.memory.textures, geometries: v.renderer.three.info.memory.geometries, listeners: v._listeners.length };
          __tf.PV.dispose(); return { hiddenVisible: hiddenBox.visible, rendersWhileHidden: renders1 - renders0, before, after: { disposed: v.disposed, rendererDisposed: v.renderer.disposed, canvases: document.querySelectorAll(".planet-sphere-canvas").length, memory: v.renderer.memoryAfterDispose, listeners: v._listeners.length, layer: !!document.getElementById("dr"), instance: BLOOM.decisionRooms.instance, pv: !!document.querySelector(".pv") } }; });
        PROOF.lifecycle = r;
        check(r.hiddenVisible === false && r.before.canvases === 1 && r.before.textures >= 1 && r.after.disposed && r.after.rendererDisposed && r.after.canvases === 0 && r.after.memory && r.after.memory.textures === 0 && r.after.memory.geometries === 0 && r.after.listeners === 0 && !r.after.layer && r.after.instance === null && !r.after.pv, // (BLOOM.planetView.instance is left by the 029B view's own dispose: pre-existing, out of 029D scope)
          `${tag} B19 · WebGL lifecycle: while the room is closed the globe's box is not visible (the renderer skips it); destroying the production Planet View disposes the rooms and the PlanetSphereView with it — view and renderer disposed, 0 sphere canvases, 0 textures / 0 geometries left on the context, 0 listeners, room layer and Planet View removed`, J(r)); }
      await p.context().close();
      // ---- B20 · anchors before any room opened (fresh page) + the shell's copies are legacy; no fake anchor
      { const q = await open("?archetype=ocean_archipelago&seed=28&ui=18");
        const r = await q.evaluate(() => { const one = n => { const e = document.querySelectorAll(`[data-tutorial="${n}"]`); return e.length === 1 && !!e[0].closest(".pv .dr .r-terraform"); }, legacy = n => document.querySelectorAll(`[data-tutorial-legacy="${n}"]`).length === 1 && !document.querySelector(`[data-tutorial-legacy="${n}"]`).closest(".pv");
          const names = ["board-terraform", "upgrade-warm", "upgrade-cool", "upgrade-humid", "upgrade-dry"], all = [...document.querySelectorAll('.pv .dr [data-tutorial^="upgrade-"]')].map(e => e.dataset.tutorial), offered = __tf.A.upgrades().flatMap(b => b.items.map(u => "upgrade-" + u.id));
          return { room: __tf.DR.state().room, ok: names.filter(one), missing: names.filter(n => !one(n)), legacy: names.filter(legacy), fake: all.filter(a => !offered.includes(a)), count: [all.length, offered.length], claimed: __tf.DR.state().claimedAnchors.filter(n => names.includes(n)).length }; });
        check(r.room === null && !r.missing.length && r.legacy.length === 5 && !r.fake.length && r.count[0] === r.count[1] && r.claimed === 5, `${tag} B20 · on a fresh page, before any room has opened, board-terraform and upgrade-warm / cool / humid / dry each resolve to ONE production element inside the Terraform room (painted at mount); the shell's copies are data-tutorial-legacy; no upgrade-* anchor exists for anything but a real offered trait`, J(r)); await q.context().close(); }
      // ---- B21 · training: paused start, Terraform opens paused with the training run's real nodes / prices, preview / purchase real, Back paused, determinism, menu
      { const q = await open("?training=1&ui=18&return=" + encodeURIComponent("/demos/main-menu.html")); await sleep(400); await frames(q, 3);
        const s0 = await state(q); await openRoom(q, "terraform"); const s1 = await q.evaluate(() => { const A = __tf.A, b = A.upgrades().find(x => x.board === "Terraform"); return { ...__tf.state(), nodes: __tf.nodes().map(n => [n.id, n.text, n.dis]), items: b.items.map(u => [u.id, u.price, u.canBuy]), simPrice: b.items.map(u => BLOOM_API.sim.price(BLOOM_API.sim.traitById[u.id])), id: __tf.identity(), planet: A.run().planetId }; });
        const n0 = await q.evaluate(() => __EV.length); await hoverNode(q, "warm"); const pv = await q.evaluate(n => __EV.slice(n).filter(e => e.type === "upgrade-preview").map(e => [e.detail.id, e.detail.available]), n0);
        if (!FF) await shot(q, "17-training-terraform-paused.png");
        await leaveTree(q); await q.click(".dr .dr-room:not([hidden]) .rb.back"); await frames(q, 3); const s2 = await state(q);
        const nodesOk = s1.items.every(([id, price, canBuy], k) => { const n = s1.nodes.find(x => x[0] === id); return n && n[1].includes(String(price)) && n[2] === String(!canBuy) && s1.simPrice[k] === price; });
        check(s0.run === false && s0.sel >= 0 && s1.dr.room === "terraform" && s1.run === false && s1.dr.wasRunning === false && s1.dr.contextId === "landing_meadow" && s1.planet === "training_grounds" && s1.id && s1.id.samePixels && s1.id.sameId && nodesOk && J(pv) === J([["warm", true]]) && s2.run === false && s2.dr.room === null,
          `${tag} B21 · training starts paused; the Terraform room opens still paused with the Training Grounds as its globe (pixel-identical to the flat training map), context Landing Meadow, its four nodes carrying the training run's real prices (= sim.price) and availability; hovering Warm fires the real preview; Back keeps training paused`, J({ ctx: s1.dr.contextId, planet: s1.planet, nodes: s1.nodes, pv }));
        const script = async (pg) => { await openRoom(pg, "terraform"); await pg.evaluate(() => { BLOOM_API.addBiomass(500); __tf.tf().paint(); }); await frames(pg, 2); await pg.click('.dr .dr-room:not([hidden]) .node[data-node="humid"]'); await frames(pg, 3); await pg.click(".dr .dr-room:not([hidden]) .rb.back"); await frames(pg, 2);
          return pg.evaluate(() => { BLOOM_API.advance(400); const s = BLOOM_API.state(), S = BLOOM_API.sim; let h = 0x811c9dc5; for (let i = 0; i < S.state.length; i++) { h ^= S.state[i]; h = Math.imul(h, 0x01000193); h ^= Math.round(S.dens[i] * 1000) & 255; h = Math.imul(h, 0x01000193); } return JSON.stringify([s.ticks, s.biomass, s.coverage, s.sky, (h >>> 0).toString(16)]); }); };
        const q2 = await open("?training=1&ui=18&return=" + encodeURIComponent("/demos/main-menu.html")); await sleep(300); const h2 = await script(q2); await q2.context().close();
        const q3 = await open("?training=1&ui=18&return=" + encodeURIComponent("/demos/main-menu.html")); await sleep(300); const h3 = await script(q3);
        check(h2 === h3 && h2.length > 10 && /"moist"/.test(h2), `${tag} B21b · deterministic training stays deterministic through the Terraform room: two fresh loads, the same Humidify purchase and 400 ticks → identical ticks, Biomass, coverage, sky and tiles`, `${h2.slice(0, 80)}…`);
        const menu = await q3.evaluate(() => [...document.querySelectorAll("#pvMenu [data-act]")].map(b => b.dataset.act));
        check(J(menu) === '["restartTraining","skipTraining","mainMenu"]' && !q.errs.length && !q3.errs.length, `${tag} B21c · Restart / Skip / Main menu remain in the training menu; training pages: no console error`, J({ menu, errs: [...q.errs, ...q3.errs] })); await q.context().close(); await q3.context().close(); }
      // ---- B22 · reduced motion
      if (!FF) { const q = await open("?archetype=ocean_archipelago&seed=28&ui=18", { rm: true }); await openRoom(q, "terraform"); await hoverNode(q, "cool");
        const r = await q.evaluate(() => ({ cls: document.querySelector(".pv").classList.contains("reduced"), anims: document.getAnimations().filter(a => a.playState === "running").length, room: __tf.DR.state().room, pv: __tf.DR.state().preview, trans: getComputedStyle(document.querySelector(".dr .lf-info")).transitionDuration, sphere: (({ reducedMotion, autoRotate, idleFactor }) => ({ reducedMotion, autoRotate, idleFactor }))(__tf.view().state()), atmoTrans: getComputedStyle(document.querySelector(".dr .tf-edges .atmo")).transitionDuration }));
        check(r.cls && r.anims === 0 && r.room === "terraform" && r.pv === "cool" && /^0s/.test(r.trans) && r.sphere.reducedMotion === true && r.sphere.autoRotate === false && r.sphere.idleFactor === 0 && /^0s/.test(r.atmoTrans), `${tag} B22 · reduced motion: the room runs no animation or transition while previewing; the sphere follows its own reduced-motion behaviour (no idle rotation, no fling)`, J(r)); await shot(q, "16-reduced-motion-terraform.png"); await q.context().close(); }
      if (FF) { const q = await open("?archetype=ocean_archipelago&seed=28&ui=18"); await openRoom(q, "terraform"); await hoverNode(q, "warm"); await shot(q, "15-firefox-1280x800-terraform.png"); await q.context().close(); }
      // ---- B23 · file:// fallback (Chromium): no crash, the mechanics stay real, a flat canonical-surface disc in the globe slot, no module request, no console error
      if (!FF) { const q = await open("?archetype=ocean_archipelago&seed=28&ui=18", { file: true }); await openRoom(q, "terraform");
        const a = await q.evaluate(() => { const g = __tf.globe(); return { kind: __tf.DR.state().globe, flat: !!__tf.room().querySelector(".tg-flat-wrap canvas"), sphereCanvas: document.querySelectorAll(".planet-sphere-canvas").length, sig: g.flat && g.flat.sig, nodes: __tf.nodes().length, soilEmpty: __tf.measure().soilEmpty, label: __tf.room().querySelector(".tg-flat-wrap").getAttribute("aria-label"), layout: !!__tf.measure().layout }; });
        const n0 = await q.evaluate(() => __EV.length); await hoverNode(q, "warm"); const b = await q.evaluate(() => ({ sig: __tf.globe().flat.sig, active: !!__tf.A.activePreview() })); await fund(q); await hoverNode(q, "warm"); await q.click('.dr .dr-room:not([hidden]) .node[data-node="warm"]'); await frames(q, 4);
        const c = await q.evaluate(n => ({ pu: __EV.slice(n).filter(e => e.type === "upgrade-purchase").map(e => e.detail.id), sky: __tf.A.hud().sky }), n0); await leaveTree(q); const d = await q.evaluate(() => __tf.globe().flat.sig);
        await shot(q, "18-file-fallback-terraform.png");
        check(a.kind === "fallback" && a.flat && a.sphereCanvas === 0 && a.nodes === 4 && a.soilEmpty && /flat/.test(a.label) && a.layout && b.sig !== a.sig && b.active && J(c.pu) === '["warm"]' && d !== a.sig && !q.reqs.some(u => /planet-sphere-view|three\.module/.test(u)) && !q.errs.length,
          `${tag} B23 · over file:// the sphere module is not requested at all; the Terraform room still opens with the same layout, a flat canonical-surface disc in the globe slot (repainting for the preview and the purchase), the four real nodes, the Soil readout; preview and purchase remain the real actions; no console error`, J({ ...a, errs: q.errs })); await q.context().close(); }
    } catch (e) { check(false, `${tag} crashed`, e.stack.split("\n").slice(0, 4).join(" | ")); }
    for (const pg of pages) await pg.context().close().catch(() => {});
    await browser.close();
  }
  server.close();
  if (EVIDENCE) { fs.writeFileSync(path.join(EVD, "terraform-proof.json"), J(PROOF, null, 2) + "\n"); console.log(`INFO  evidence written to docs/evidence/bloom-029d/`); }
  console.log(`\n${fails ? `${fails} check(s) FAILED` : "ALL CHECKS PASS"}  (${((Date.now() - t0) / 1000).toFixed(1)} s)`);
  process.exit(fails ? 1 : 0);
})().catch(e => { console.log("FAIL  crashed — " + e.stack); console.log("\n1 check(s) FAILED"); process.exit(1); });
